// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs3/sharing/link/v1beta1/link_api.proto

package linkv1beta1

import (
	context "context"
	fmt "fmt"
	v1beta13 "github.com/cs3org/go-cs3apis/cs3/identity/user/v1beta1"
	v1beta12 "github.com/cs3org/go-cs3apis/cs3/rpc/v1beta1"
	v1beta11 "github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"
	v1beta1 "github.com/cs3org/go-cs3apis/cs3/types/v1beta1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// REQUIRED.
type UpdatePublicShareRequest_Update_Type int32

const (
	UpdatePublicShareRequest_Update_TYPE_INVALID     UpdatePublicShareRequest_Update_Type = 0
	UpdatePublicShareRequest_Update_TYPE_PERMISSIONS UpdatePublicShareRequest_Update_Type = 1
	UpdatePublicShareRequest_Update_TYPE_PASSWORD    UpdatePublicShareRequest_Update_Type = 2
	UpdatePublicShareRequest_Update_TYPE_EXPIRATION  UpdatePublicShareRequest_Update_Type = 3
	UpdatePublicShareRequest_Update_TYPE_DISPLAYNAME UpdatePublicShareRequest_Update_Type = 4
)

var UpdatePublicShareRequest_Update_Type_name = map[int32]string{
	0: "TYPE_INVALID",
	1: "TYPE_PERMISSIONS",
	2: "TYPE_PASSWORD",
	3: "TYPE_EXPIRATION",
	4: "TYPE_DISPLAYNAME",
}

var UpdatePublicShareRequest_Update_Type_value = map[string]int32{
	"TYPE_INVALID":     0,
	"TYPE_PERMISSIONS": 1,
	"TYPE_PASSWORD":    2,
	"TYPE_EXPIRATION":  3,
	"TYPE_DISPLAYNAME": 4,
}

func (x UpdatePublicShareRequest_Update_Type) String() string {
	return proto.EnumName(UpdatePublicShareRequest_Update_Type_name, int32(x))
}

func (UpdatePublicShareRequest_Update_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{2, 0, 0}
}

// REQUIRED.
type ListPublicSharesRequest_Filter_Type int32

const (
	ListPublicSharesRequest_Filter_TYPE_INVALID   ListPublicSharesRequest_Filter_Type = 0
	ListPublicSharesRequest_Filter_TYPE_REFERENCE ListPublicSharesRequest_Filter_Type = 1
	ListPublicSharesRequest_Filter_TYPE_OWNER     ListPublicSharesRequest_Filter_Type = 2
	ListPublicSharesRequest_Filter_TYPE_CREATOR   ListPublicSharesRequest_Filter_Type = 3
)

var ListPublicSharesRequest_Filter_Type_name = map[int32]string{
	0: "TYPE_INVALID",
	1: "TYPE_REFERENCE",
	2: "TYPE_OWNER",
	3: "TYPE_CREATOR",
}

var ListPublicSharesRequest_Filter_Type_value = map[string]int32{
	"TYPE_INVALID":   0,
	"TYPE_REFERENCE": 1,
	"TYPE_OWNER":     2,
	"TYPE_CREATOR":   3,
}

func (x ListPublicSharesRequest_Filter_Type) String() string {
	return proto.EnumName(ListPublicSharesRequest_Filter_Type_name, int32(x))
}

func (ListPublicSharesRequest_Filter_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{4, 0, 0}
}

type CreatePublicShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The unique identifier for the shared storage resource.
	ResourceInfo *v1beta11.ResourceInfo `protobuf:"bytes,2,opt,name=resource_info,json=resourceInfo,proto3" json:"resource_info,omitempty"`
	// REQUIRED.
	// The restrictions to apply to the share.
	Grant                *Grant   `protobuf:"bytes,3,opt,name=grant,proto3" json:"grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePublicShareRequest) Reset()         { *m = CreatePublicShareRequest{} }
func (m *CreatePublicShareRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePublicShareRequest) ProtoMessage()    {}
func (*CreatePublicShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{0}
}

func (m *CreatePublicShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePublicShareRequest.Unmarshal(m, b)
}
func (m *CreatePublicShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePublicShareRequest.Marshal(b, m, deterministic)
}
func (m *CreatePublicShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePublicShareRequest.Merge(m, src)
}
func (m *CreatePublicShareRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePublicShareRequest.Size(m)
}
func (m *CreatePublicShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePublicShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePublicShareRequest proto.InternalMessageInfo

func (m *CreatePublicShareRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *CreatePublicShareRequest) GetResourceInfo() *v1beta11.ResourceInfo {
	if m != nil {
		return m.ResourceInfo
	}
	return nil
}

func (m *CreatePublicShareRequest) GetGrant() *Grant {
	if m != nil {
		return m.Grant
	}
	return nil
}

type CreatePublicShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The created share.
	Share                *PublicShare `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreatePublicShareResponse) Reset()         { *m = CreatePublicShareResponse{} }
func (m *CreatePublicShareResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePublicShareResponse) ProtoMessage()    {}
func (*CreatePublicShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{1}
}

func (m *CreatePublicShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePublicShareResponse.Unmarshal(m, b)
}
func (m *CreatePublicShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePublicShareResponse.Marshal(b, m, deterministic)
}
func (m *CreatePublicShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePublicShareResponse.Merge(m, src)
}
func (m *CreatePublicShareResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePublicShareResponse.Size(m)
}
func (m *CreatePublicShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePublicShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePublicShareResponse proto.InternalMessageInfo

func (m *CreatePublicShareResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreatePublicShareResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *CreatePublicShareResponse) GetShare() *PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

type UpdatePublicShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The reference to the public share.
	Ref                  *PublicShareReference            `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Update               *UpdatePublicShareRequest_Update `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *UpdatePublicShareRequest) Reset()         { *m = UpdatePublicShareRequest{} }
func (m *UpdatePublicShareRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePublicShareRequest) ProtoMessage()    {}
func (*UpdatePublicShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{2}
}

func (m *UpdatePublicShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePublicShareRequest.Unmarshal(m, b)
}
func (m *UpdatePublicShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePublicShareRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePublicShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePublicShareRequest.Merge(m, src)
}
func (m *UpdatePublicShareRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePublicShareRequest.Size(m)
}
func (m *UpdatePublicShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePublicShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePublicShareRequest proto.InternalMessageInfo

func (m *UpdatePublicShareRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *UpdatePublicShareRequest) GetRef() *PublicShareReference {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *UpdatePublicShareRequest) GetUpdate() *UpdatePublicShareRequest_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

// REQUIRED.
type UpdatePublicShareRequest_Update struct {
	// REQUIRED.
	// Defines the field to update.
	Type UpdatePublicShareRequest_Update_Type `protobuf:"varint,3,opt,name=type,proto3,enum=cs3.sharing.link.v1beta1.UpdatePublicShareRequest_Update_Type" json:"type,omitempty"`
	// REQUIRED.
	// Contains the field that will be updated.
	Grant *Grant `protobuf:"bytes,4,opt,name=grant,proto3" json:"grant,omitempty"`
	// OPTIONAL
	// Defines the public link display name.
	DisplayName          string   `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePublicShareRequest_Update) Reset()         { *m = UpdatePublicShareRequest_Update{} }
func (m *UpdatePublicShareRequest_Update) String() string { return proto.CompactTextString(m) }
func (*UpdatePublicShareRequest_Update) ProtoMessage()    {}
func (*UpdatePublicShareRequest_Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{2, 0}
}

func (m *UpdatePublicShareRequest_Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePublicShareRequest_Update.Unmarshal(m, b)
}
func (m *UpdatePublicShareRequest_Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePublicShareRequest_Update.Marshal(b, m, deterministic)
}
func (m *UpdatePublicShareRequest_Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePublicShareRequest_Update.Merge(m, src)
}
func (m *UpdatePublicShareRequest_Update) XXX_Size() int {
	return xxx_messageInfo_UpdatePublicShareRequest_Update.Size(m)
}
func (m *UpdatePublicShareRequest_Update) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePublicShareRequest_Update.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePublicShareRequest_Update proto.InternalMessageInfo

func (m *UpdatePublicShareRequest_Update) GetType() UpdatePublicShareRequest_Update_Type {
	if m != nil {
		return m.Type
	}
	return UpdatePublicShareRequest_Update_TYPE_INVALID
}

func (m *UpdatePublicShareRequest_Update) GetGrant() *Grant {
	if m != nil {
		return m.Grant
	}
	return nil
}

func (m *UpdatePublicShareRequest_Update) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type UpdatePublicShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The updated public share.
	Share                *PublicShare `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdatePublicShareResponse) Reset()         { *m = UpdatePublicShareResponse{} }
func (m *UpdatePublicShareResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePublicShareResponse) ProtoMessage()    {}
func (*UpdatePublicShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{3}
}

func (m *UpdatePublicShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePublicShareResponse.Unmarshal(m, b)
}
func (m *UpdatePublicShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePublicShareResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePublicShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePublicShareResponse.Merge(m, src)
}
func (m *UpdatePublicShareResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePublicShareResponse.Size(m)
}
func (m *UpdatePublicShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePublicShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePublicShareResponse proto.InternalMessageInfo

func (m *UpdatePublicShareResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdatePublicShareResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *UpdatePublicShareResponse) GetShare() *PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

type ListPublicSharesRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// OPTIONAL.
	// The list of filters to apply if any.
	Filters []*ListPublicSharesRequest_Filter `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	// OPTIONAL.
	// If a signature should be included in the share.
	Sign                 bool     `protobuf:"varint,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPublicSharesRequest) Reset()         { *m = ListPublicSharesRequest{} }
func (m *ListPublicSharesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPublicSharesRequest) ProtoMessage()    {}
func (*ListPublicSharesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{4}
}

func (m *ListPublicSharesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublicSharesRequest.Unmarshal(m, b)
}
func (m *ListPublicSharesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublicSharesRequest.Marshal(b, m, deterministic)
}
func (m *ListPublicSharesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublicSharesRequest.Merge(m, src)
}
func (m *ListPublicSharesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPublicSharesRequest.Size(m)
}
func (m *ListPublicSharesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublicSharesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublicSharesRequest proto.InternalMessageInfo

func (m *ListPublicSharesRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *ListPublicSharesRequest) GetFilters() []*ListPublicSharesRequest_Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ListPublicSharesRequest) GetSign() bool {
	if m != nil {
		return m.Sign
	}
	return false
}

// REQUIRED.
// represents a filter to apply to the request.
type ListPublicSharesRequest_Filter struct {
	Type ListPublicSharesRequest_Filter_Type `protobuf:"varint,2,opt,name=type,proto3,enum=cs3.sharing.link.v1beta1.ListPublicSharesRequest_Filter_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Term:
	//	*ListPublicSharesRequest_Filter_Ref
	//	*ListPublicSharesRequest_Filter_Owner
	//	*ListPublicSharesRequest_Filter_Creator
	Term                 isListPublicSharesRequest_Filter_Term `protobuf_oneof:"term"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ListPublicSharesRequest_Filter) Reset()         { *m = ListPublicSharesRequest_Filter{} }
func (m *ListPublicSharesRequest_Filter) String() string { return proto.CompactTextString(m) }
func (*ListPublicSharesRequest_Filter) ProtoMessage()    {}
func (*ListPublicSharesRequest_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{4, 0}
}

func (m *ListPublicSharesRequest_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublicSharesRequest_Filter.Unmarshal(m, b)
}
func (m *ListPublicSharesRequest_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublicSharesRequest_Filter.Marshal(b, m, deterministic)
}
func (m *ListPublicSharesRequest_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublicSharesRequest_Filter.Merge(m, src)
}
func (m *ListPublicSharesRequest_Filter) XXX_Size() int {
	return xxx_messageInfo_ListPublicSharesRequest_Filter.Size(m)
}
func (m *ListPublicSharesRequest_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublicSharesRequest_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublicSharesRequest_Filter proto.InternalMessageInfo

func (m *ListPublicSharesRequest_Filter) GetType() ListPublicSharesRequest_Filter_Type {
	if m != nil {
		return m.Type
	}
	return ListPublicSharesRequest_Filter_TYPE_INVALID
}

type isListPublicSharesRequest_Filter_Term interface {
	isListPublicSharesRequest_Filter_Term()
}

type ListPublicSharesRequest_Filter_Ref struct {
	Ref *v1beta11.Reference `protobuf:"bytes,3,opt,name=ref,proto3,oneof"`
}

type ListPublicSharesRequest_Filter_Owner struct {
	Owner *v1beta13.UserId `protobuf:"bytes,4,opt,name=owner,proto3,oneof"`
}

type ListPublicSharesRequest_Filter_Creator struct {
	Creator *v1beta13.UserId `protobuf:"bytes,5,opt,name=creator,proto3,oneof"`
}

func (*ListPublicSharesRequest_Filter_Ref) isListPublicSharesRequest_Filter_Term() {}

func (*ListPublicSharesRequest_Filter_Owner) isListPublicSharesRequest_Filter_Term() {}

func (*ListPublicSharesRequest_Filter_Creator) isListPublicSharesRequest_Filter_Term() {}

func (m *ListPublicSharesRequest_Filter) GetTerm() isListPublicSharesRequest_Filter_Term {
	if m != nil {
		return m.Term
	}
	return nil
}

func (m *ListPublicSharesRequest_Filter) GetRef() *v1beta11.Reference {
	if x, ok := m.GetTerm().(*ListPublicSharesRequest_Filter_Ref); ok {
		return x.Ref
	}
	return nil
}

func (m *ListPublicSharesRequest_Filter) GetOwner() *v1beta13.UserId {
	if x, ok := m.GetTerm().(*ListPublicSharesRequest_Filter_Owner); ok {
		return x.Owner
	}
	return nil
}

func (m *ListPublicSharesRequest_Filter) GetCreator() *v1beta13.UserId {
	if x, ok := m.GetTerm().(*ListPublicSharesRequest_Filter_Creator); ok {
		return x.Creator
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListPublicSharesRequest_Filter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListPublicSharesRequest_Filter_Ref)(nil),
		(*ListPublicSharesRequest_Filter_Owner)(nil),
		(*ListPublicSharesRequest_Filter_Creator)(nil),
	}
}

type ListPublicSharesResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The list of shares.
	Share                []*PublicShare `protobuf:"bytes,3,rep,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPublicSharesResponse) Reset()         { *m = ListPublicSharesResponse{} }
func (m *ListPublicSharesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPublicSharesResponse) ProtoMessage()    {}
func (*ListPublicSharesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{5}
}

func (m *ListPublicSharesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublicSharesResponse.Unmarshal(m, b)
}
func (m *ListPublicSharesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublicSharesResponse.Marshal(b, m, deterministic)
}
func (m *ListPublicSharesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublicSharesResponse.Merge(m, src)
}
func (m *ListPublicSharesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPublicSharesResponse.Size(m)
}
func (m *ListPublicSharesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublicSharesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublicSharesResponse proto.InternalMessageInfo

func (m *ListPublicSharesResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPublicSharesResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *ListPublicSharesResponse) GetShare() []*PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

type RemovePublicShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The reference to which the action should be performed.
	Ref                  *PublicShareReference `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RemovePublicShareRequest) Reset()         { *m = RemovePublicShareRequest{} }
func (m *RemovePublicShareRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePublicShareRequest) ProtoMessage()    {}
func (*RemovePublicShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{6}
}

func (m *RemovePublicShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePublicShareRequest.Unmarshal(m, b)
}
func (m *RemovePublicShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePublicShareRequest.Marshal(b, m, deterministic)
}
func (m *RemovePublicShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePublicShareRequest.Merge(m, src)
}
func (m *RemovePublicShareRequest) XXX_Size() int {
	return xxx_messageInfo_RemovePublicShareRequest.Size(m)
}
func (m *RemovePublicShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePublicShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePublicShareRequest proto.InternalMessageInfo

func (m *RemovePublicShareRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *RemovePublicShareRequest) GetRef() *PublicShareReference {
	if m != nil {
		return m.Ref
	}
	return nil
}

type RemovePublicShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque               *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RemovePublicShareResponse) Reset()         { *m = RemovePublicShareResponse{} }
func (m *RemovePublicShareResponse) String() string { return proto.CompactTextString(m) }
func (*RemovePublicShareResponse) ProtoMessage()    {}
func (*RemovePublicShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{7}
}

func (m *RemovePublicShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePublicShareResponse.Unmarshal(m, b)
}
func (m *RemovePublicShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePublicShareResponse.Marshal(b, m, deterministic)
}
func (m *RemovePublicShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePublicShareResponse.Merge(m, src)
}
func (m *RemovePublicShareResponse) XXX_Size() int {
	return xxx_messageInfo_RemovePublicShareResponse.Size(m)
}
func (m *RemovePublicShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePublicShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePublicShareResponse proto.InternalMessageInfo

func (m *RemovePublicShareResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RemovePublicShareResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

type GetPublicShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The reference to which the action should be performed.
	Ref *PublicShareReference `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	// OPTIONAL.
	// If a signature should be included in the share.
	Sign                 bool     `protobuf:"varint,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPublicShareRequest) Reset()         { *m = GetPublicShareRequest{} }
func (m *GetPublicShareRequest) String() string { return proto.CompactTextString(m) }
func (*GetPublicShareRequest) ProtoMessage()    {}
func (*GetPublicShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{8}
}

func (m *GetPublicShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicShareRequest.Unmarshal(m, b)
}
func (m *GetPublicShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicShareRequest.Marshal(b, m, deterministic)
}
func (m *GetPublicShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicShareRequest.Merge(m, src)
}
func (m *GetPublicShareRequest) XXX_Size() int {
	return xxx_messageInfo_GetPublicShareRequest.Size(m)
}
func (m *GetPublicShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicShareRequest proto.InternalMessageInfo

func (m *GetPublicShareRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetPublicShareRequest) GetRef() *PublicShareReference {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *GetPublicShareRequest) GetSign() bool {
	if m != nil {
		return m.Sign
	}
	return false
}

type GetPublicShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The share.
	Share                *PublicShare `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPublicShareResponse) Reset()         { *m = GetPublicShareResponse{} }
func (m *GetPublicShareResponse) String() string { return proto.CompactTextString(m) }
func (*GetPublicShareResponse) ProtoMessage()    {}
func (*GetPublicShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{9}
}

func (m *GetPublicShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicShareResponse.Unmarshal(m, b)
}
func (m *GetPublicShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicShareResponse.Marshal(b, m, deterministic)
}
func (m *GetPublicShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicShareResponse.Merge(m, src)
}
func (m *GetPublicShareResponse) XXX_Size() int {
	return xxx_messageInfo_GetPublicShareResponse.Size(m)
}
func (m *GetPublicShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicShareResponse proto.InternalMessageInfo

func (m *GetPublicShareResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPublicShareResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetPublicShareResponse) GetShare() *PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

type GetPublicShareByTokenRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The unlisted token to identify the public share.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// OPTIONAL.
	// The public link can require authentication.
	Authentication *PublicShareAuthentication `protobuf:"bytes,3,opt,name=authentication,proto3" json:"authentication,omitempty"`
	// OPTIONAL.
	// If a signature should be included in the share.
	Sign                 bool     `protobuf:"varint,4,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPublicShareByTokenRequest) Reset()         { *m = GetPublicShareByTokenRequest{} }
func (m *GetPublicShareByTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetPublicShareByTokenRequest) ProtoMessage()    {}
func (*GetPublicShareByTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{10}
}

func (m *GetPublicShareByTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicShareByTokenRequest.Unmarshal(m, b)
}
func (m *GetPublicShareByTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicShareByTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetPublicShareByTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicShareByTokenRequest.Merge(m, src)
}
func (m *GetPublicShareByTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetPublicShareByTokenRequest.Size(m)
}
func (m *GetPublicShareByTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicShareByTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicShareByTokenRequest proto.InternalMessageInfo

func (m *GetPublicShareByTokenRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetPublicShareByTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetPublicShareByTokenRequest) GetAuthentication() *PublicShareAuthentication {
	if m != nil {
		return m.Authentication
	}
	return nil
}

func (m *GetPublicShareByTokenRequest) GetSign() bool {
	if m != nil {
		return m.Sign
	}
	return false
}

type GetPublicShareByTokenResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The share.
	Share *PublicShare `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	// OPTIONAL.
	// The share password hash.
	PasswordHash         string   `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPublicShareByTokenResponse) Reset()         { *m = GetPublicShareByTokenResponse{} }
func (m *GetPublicShareByTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetPublicShareByTokenResponse) ProtoMessage()    {}
func (*GetPublicShareByTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd835bb71eb73d1e, []int{11}
}

func (m *GetPublicShareByTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicShareByTokenResponse.Unmarshal(m, b)
}
func (m *GetPublicShareByTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicShareByTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetPublicShareByTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicShareByTokenResponse.Merge(m, src)
}
func (m *GetPublicShareByTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetPublicShareByTokenResponse.Size(m)
}
func (m *GetPublicShareByTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicShareByTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicShareByTokenResponse proto.InternalMessageInfo

func (m *GetPublicShareByTokenResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPublicShareByTokenResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetPublicShareByTokenResponse) GetShare() *PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

// Deprecated: Do not use.
func (m *GetPublicShareByTokenResponse) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func init() {
	proto.RegisterEnum("cs3.sharing.link.v1beta1.UpdatePublicShareRequest_Update_Type", UpdatePublicShareRequest_Update_Type_name, UpdatePublicShareRequest_Update_Type_value)
	proto.RegisterEnum("cs3.sharing.link.v1beta1.ListPublicSharesRequest_Filter_Type", ListPublicSharesRequest_Filter_Type_name, ListPublicSharesRequest_Filter_Type_value)
	proto.RegisterType((*CreatePublicShareRequest)(nil), "cs3.sharing.link.v1beta1.CreatePublicShareRequest")
	proto.RegisterType((*CreatePublicShareResponse)(nil), "cs3.sharing.link.v1beta1.CreatePublicShareResponse")
	proto.RegisterType((*UpdatePublicShareRequest)(nil), "cs3.sharing.link.v1beta1.UpdatePublicShareRequest")
	proto.RegisterType((*UpdatePublicShareRequest_Update)(nil), "cs3.sharing.link.v1beta1.UpdatePublicShareRequest.Update")
	proto.RegisterType((*UpdatePublicShareResponse)(nil), "cs3.sharing.link.v1beta1.UpdatePublicShareResponse")
	proto.RegisterType((*ListPublicSharesRequest)(nil), "cs3.sharing.link.v1beta1.ListPublicSharesRequest")
	proto.RegisterType((*ListPublicSharesRequest_Filter)(nil), "cs3.sharing.link.v1beta1.ListPublicSharesRequest.Filter")
	proto.RegisterType((*ListPublicSharesResponse)(nil), "cs3.sharing.link.v1beta1.ListPublicSharesResponse")
	proto.RegisterType((*RemovePublicShareRequest)(nil), "cs3.sharing.link.v1beta1.RemovePublicShareRequest")
	proto.RegisterType((*RemovePublicShareResponse)(nil), "cs3.sharing.link.v1beta1.RemovePublicShareResponse")
	proto.RegisterType((*GetPublicShareRequest)(nil), "cs3.sharing.link.v1beta1.GetPublicShareRequest")
	proto.RegisterType((*GetPublicShareResponse)(nil), "cs3.sharing.link.v1beta1.GetPublicShareResponse")
	proto.RegisterType((*GetPublicShareByTokenRequest)(nil), "cs3.sharing.link.v1beta1.GetPublicShareByTokenRequest")
	proto.RegisterType((*GetPublicShareByTokenResponse)(nil), "cs3.sharing.link.v1beta1.GetPublicShareByTokenResponse")
}

func init() {
	proto.RegisterFile("cs3/sharing/link/v1beta1/link_api.proto", fileDescriptor_fd835bb71eb73d1e)
}

var fileDescriptor_fd835bb71eb73d1e = []byte{
	// 1043 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xee, 0xae, 0x7f, 0x42, 0x4e, 0x7e, 0xd8, 0x0c, 0x85, 0x6e, 0xac, 0x54, 0xa4, 0x96, 0x50,
	0x02, 0x42, 0x6b, 0x62, 0x8b, 0x9f, 0xaa, 0x2a, 0xc2, 0x76, 0xb6, 0xcd, 0x4a, 0xae, 0xed, 0xce,
	0x9a, 0x96, 0x42, 0x24, 0x6b, 0xb3, 0x1e, 0xc7, 0xab, 0xd8, 0xbb, 0xdb, 0x99, 0x75, 0x22, 0x4b,
	0x95, 0xb8, 0x85, 0x2b, 0x5e, 0x01, 0x10, 0x57, 0xbc, 0x01, 0x82, 0x27, 0xe0, 0x1e, 0x89, 0x57,
	0x80, 0x87, 0x40, 0x68, 0x67, 0xc7, 0x8e, 0x13, 0x7b, 0x8d, 0xdd, 0x22, 0x68, 0xee, 0xbc, 0x73,
	0xce, 0xf7, 0xcd, 0x77, 0x7e, 0xe6, 0xcc, 0x18, 0x76, 0x6c, 0x56, 0xc8, 0xb1, 0x8e, 0x45, 0x1d,
	0xf7, 0x38, 0xd7, 0x75, 0xdc, 0x93, 0xdc, 0xe9, 0xde, 0x11, 0x09, 0xac, 0x3d, 0xfe, 0xd1, 0xb4,
	0x7c, 0x47, 0xf3, 0xa9, 0x17, 0x78, 0x48, 0xb5, 0x59, 0x41, 0x13, 0x8e, 0x5a, 0x68, 0xd3, 0x84,
	0x63, 0xe6, 0xed, 0x90, 0xc2, 0x69, 0x11, 0x37, 0x70, 0x82, 0x41, 0xae, 0xcf, 0x08, 0x1d, 0x71,
	0x50, 0xc2, 0xbc, 0x3e, 0xb5, 0x09, 0x8b, 0x48, 0x32, 0x5b, 0xa1, 0x2b, 0xf5, 0xed, 0x91, 0x03,
	0x0b, 0xac, 0xa0, 0x3f, 0xb4, 0xee, 0xc6, 0x6a, 0xb9, 0xcc, 0xf3, 0x2e, 0xf7, 0x0c, 0x3c, 0x6a,
	0x1d, 0x93, 0x9c, 0x4f, 0xbd, 0x53, 0xa7, 0x35, 0x63, 0xd7, 0x9b, 0xa1, 0x77, 0x30, 0xf0, 0x09,
	0x1b, 0xb9, 0xf0, 0xaf, 0xc8, 0x9c, 0xfd, 0x4d, 0x02, 0xb5, 0x4c, 0x89, 0x15, 0x90, 0x7a, 0xff,
	0xa8, 0xeb, 0xd8, 0x66, 0xc7, 0xa2, 0x04, 0x93, 0xa7, 0x7d, 0xc2, 0x02, 0xb4, 0x07, 0x69, 0xcf,
	0xb7, 0x9e, 0xf6, 0x89, 0x2a, 0x6d, 0x4b, 0xbb, 0x2b, 0xf9, 0x4d, 0x2d, 0xcc, 0x43, 0x04, 0x17,
	0x64, 0x5a, 0x8d, 0x3b, 0x60, 0xe1, 0x88, 0x6a, 0xb0, 0x36, 0x54, 0xd0, 0x74, 0xdc, 0xb6, 0xa7,
	0xca, 0x1c, 0xf9, 0x0e, 0x47, 0x0a, 0xd1, 0xda, 0x50, 0xf4, 0x88, 0x04, 0x0b, 0x88, 0xe1, 0xb6,
	0x3d, 0xbc, 0x4a, 0xc7, 0xbe, 0xd0, 0xfb, 0x90, 0x3a, 0xa6, 0x96, 0x1b, 0xa8, 0x09, 0x4e, 0xf4,
	0xa6, 0x16, 0x57, 0x0a, 0xed, 0x7e, 0xe8, 0x86, 0x23, 0xef, 0xec, 0x2f, 0x12, 0x6c, 0x4e, 0x89,
	0x8b, 0xf9, 0x9e, 0xcb, 0x08, 0xca, 0x41, 0x3a, 0x4a, 0xbe, 0x08, 0xec, 0x06, 0x67, 0xa5, 0xbe,
	0x3d, 0x22, 0x33, 0xb9, 0x19, 0x0b, 0xb7, 0xb1, 0x4c, 0xc8, 0xf3, 0x66, 0xe2, 0x0e, 0xa4, 0x42,
	0x99, 0x44, 0x08, 0x7f, 0x2b, 0x5e, 0xf8, 0xb8, 0xc2, 0x08, 0x93, 0xfd, 0x3a, 0x09, 0xea, 0xa7,
	0x7e, 0xeb, 0x5f, 0x2b, 0xcb, 0x27, 0x90, 0xa0, 0xa4, 0x2d, 0xc4, 0x6b, 0xf3, 0x49, 0x21, 0x6d,
	0x42, 0x89, 0x6b, 0x13, 0x1c, 0x42, 0xd1, 0x43, 0x48, 0xf7, 0xb9, 0x20, 0x11, 0xcf, 0xed, 0x78,
	0x92, 0x38, 0xe1, 0xc2, 0x80, 0x05, 0x51, 0xe6, 0x07, 0x19, 0xd2, 0xd1, 0x12, 0xc2, 0x90, 0x0c,
	0xf5, 0x73, 0xee, 0xf5, 0xfc, 0xc7, 0xcf, 0xcd, 0xad, 0x35, 0x06, 0x3e, 0xc1, 0x9c, 0xeb, 0xbc,
	0x73, 0x92, 0x8b, 0x74, 0x0e, 0xba, 0x05, 0xab, 0x2d, 0x87, 0xf9, 0x5d, 0x6b, 0xd0, 0x74, 0xad,
	0x1e, 0x51, 0x53, 0xdb, 0xd2, 0xee, 0x32, 0x5e, 0x11, 0x6b, 0x55, 0xab, 0x47, 0xb2, 0x5d, 0x48,
	0x86, 0xfb, 0x20, 0x05, 0x56, 0x1b, 0x4f, 0xea, 0x7a, 0xd3, 0xa8, 0x3e, 0x2a, 0x56, 0x8c, 0x7d,
	0xe5, 0x1a, 0xba, 0x0e, 0x0a, 0x5f, 0xa9, 0xeb, 0xf8, 0x81, 0x61, 0x9a, 0x46, 0xad, 0x6a, 0x2a,
	0x12, 0xda, 0x80, 0xb5, 0x68, 0xb5, 0x68, 0x9a, 0x8f, 0x6b, 0x78, 0x5f, 0x91, 0xd1, 0x6b, 0xf0,
	0x2a, 0x5f, 0xd2, 0x3f, 0xab, 0x1b, 0xb8, 0xd8, 0x30, 0x6a, 0x55, 0x25, 0x31, 0x42, 0xef, 0x1b,
	0x66, 0xbd, 0x52, 0x7c, 0x52, 0x2d, 0x3e, 0xd0, 0x95, 0x24, 0x6f, 0xe5, 0x29, 0x61, 0x5f, 0x95,
	0x56, 0xfe, 0x2e, 0x09, 0x37, 0x2a, 0x0e, 0x0b, 0xc6, 0x4c, 0xec, 0x05, 0x3a, 0x19, 0xc3, 0x52,
	0xdb, 0xe9, 0x06, 0x84, 0x32, 0x55, 0xde, 0x4e, 0xec, 0xae, 0xe4, 0x3f, 0x8a, 0x57, 0x13, 0xb3,
	0xad, 0x76, 0x8f, 0x13, 0xe0, 0x21, 0x11, 0x42, 0x90, 0x64, 0xce, 0xb1, 0xcb, 0xc3, 0x7b, 0x05,
	0xf3, 0xdf, 0x99, 0x3f, 0x65, 0x48, 0x47, 0x7e, 0xe8, 0xa1, 0x68, 0x4e, 0x99, 0x37, 0xe7, 0xdd,
	0xe7, 0xdd, 0x6f, 0xbc, 0x37, 0xef, 0x44, 0xe7, 0x31, 0xca, 0xe7, 0xce, 0x3f, 0x0d, 0x47, 0x71,
	0x10, 0x0f, 0xae, 0x45, 0x47, 0xf1, 0x36, 0xa4, 0xbc, 0x33, 0x97, 0x50, 0xd1, 0xd8, 0xb7, 0x38,
	0x7c, 0x78, 0x07, 0x69, 0xe1, 0x1d, 0x74, 0x7e, 0x5c, 0x18, 0xa1, 0x46, 0xeb, 0xe0, 0x1a, 0x8e,
	0x10, 0xe8, 0x2e, 0x2c, 0xd9, 0xe1, 0x54, 0xf4, 0x28, 0xef, 0xeb, 0x39, 0xc1, 0x43, 0x4c, 0xb6,
	0x1a, 0xdb, 0xf8, 0x08, 0xd6, 0xf9, 0x0a, 0xd6, 0xef, 0xe9, 0x58, 0xaf, 0x96, 0x75, 0x45, 0x42,
	0xeb, 0x00, 0x7c, 0xad, 0xf6, 0xb8, 0xaa, 0x63, 0x45, 0x1e, 0xa1, 0xca, 0x58, 0x2f, 0x36, 0x6a,
	0x58, 0x49, 0x94, 0xd2, 0x90, 0x0c, 0x08, 0xed, 0x65, 0x7f, 0x96, 0x40, 0x9d, 0x4c, 0xde, 0xff,
	0xd3, 0xe1, 0x89, 0x85, 0x3b, 0xfc, 0x1b, 0x09, 0x54, 0x4c, 0x7a, 0xde, 0xe9, 0xcb, 0x32, 0xac,
	0xb3, 0x5f, 0xc2, 0xe6, 0x14, 0x41, 0xff, 0x5d, 0x3e, 0xb3, 0xdf, 0x4a, 0xf0, 0xfa, 0x7d, 0x12,
	0xbc, 0x2c, 0x97, 0xd7, 0x94, 0x03, 0x9e, 0xfd, 0x49, 0x82, 0x37, 0x2e, 0x4b, 0xbc, 0x2a, 0x33,
	0xf5, 0x77, 0x09, 0xb6, 0x2e, 0x6a, 0x2f, 0x0d, 0x1a, 0xde, 0x09, 0x71, 0x5f, 0x20, 0xcb, 0xd7,
	0x21, 0x15, 0x84, 0x14, 0x3c, 0x84, 0x65, 0x1c, 0x7d, 0xa0, 0x2f, 0x60, 0xdd, 0xea, 0x07, 0x9d,
	0x70, 0x3c, 0xd8, 0x56, 0xe0, 0x78, 0xae, 0xd0, 0x5b, 0x98, 0x4b, 0x6f, 0xf1, 0x02, 0x14, 0x5f,
	0xa2, 0x1a, 0x95, 0x25, 0x39, 0x56, 0x96, 0x3f, 0x24, 0xb8, 0x19, 0x13, 0xda, 0x15, 0xa9, 0x0e,
	0xda, 0x81, 0x35, 0xdf, 0x62, 0xec, 0xcc, 0xa3, 0xad, 0x66, 0xc7, 0x62, 0x1d, 0x1e, 0xdf, 0x72,
	0x49, 0x56, 0x25, 0xbc, 0x3a, 0x34, 0x1c, 0x58, 0xac, 0x93, 0xff, 0x2b, 0x05, 0x4b, 0x15, 0xc7,
	0x3d, 0x29, 0xd6, 0x0d, 0xf4, 0x0c, 0x36, 0x26, 0xde, 0xab, 0x28, 0x1f, 0xbf, 0x6f, 0xdc, 0xa3,
	0x3d, 0x53, 0x58, 0x08, 0x23, 0x72, 0xfa, 0x0c, 0x36, 0x26, 0x06, 0xc6, 0xac, 0xdd, 0xe3, 0xc6,
	0xdd, 0xac, 0xdd, 0xe3, 0x27, 0x12, 0x83, 0xf5, 0x8b, 0x25, 0x47, 0xb9, 0x19, 0x8f, 0xb5, 0x69,
	0x63, 0x25, 0xf3, 0xde, 0xfc, 0x00, 0xb1, 0xe9, 0x57, 0x13, 0x23, 0x4a, 0x34, 0x1a, 0xfa, 0x60,
	0x5e, 0xae, 0x8b, 0x87, 0x2e, 0xf3, 0xe1, 0xc2, 0x38, 0x21, 0x65, 0x00, 0xca, 0xe5, 0xdb, 0x0f,
	0xed, 0x2d, 0xfc, 0xcc, 0xc8, 0xe4, 0x17, 0x81, 0x9c, 0x17, 0x7e, 0xe2, 0x6d, 0x39, 0xab, 0xf0,
	0x71, 0xef, 0xef, 0x59, 0x85, 0x8f, 0x7d, 0xbc, 0x96, 0xce, 0x60, 0xcb, 0xf6, 0x7a, 0xb1, 0xc8,
	0xd2, 0x2a, 0x3f, 0x1d, 0xbe, 0x53, 0x0f, 0xff, 0xab, 0xd6, 0xa5, 0xcf, 0x57, 0x42, 0xab, 0x30,
	0x7e, 0x2f, 0x27, 0xca, 0x66, 0xe5, 0x47, 0x59, 0x2d, 0xb3, 0x82, 0x66, 0x0a, 0x74, 0xe8, 0xaf,
	0x3d, 0xda, 0x2b, 0x85, 0x0e, 0xbf, 0x72, 0xd3, 0xa1, 0x30, 0x1d, 0x86, 0xa6, 0x43, 0x61, 0x3a,
	0x4a, 0xf3, 0x7f, 0xbf, 0x85, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x31, 0x62, 0x67, 0x02,
	0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LinkAPIClient is the client API for LinkAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinkAPIClient interface {
	// Creates a new share.
	// MUST return CODE_NOT_FOUND if the resource reference does not exist.
	// MUST return CODE_ALREADY_EXISTS if the share already exists for the 4-tuple consisting of
	// (owner, shared_resource, grantee).
	// New shares MUST be created in the state SHARE_STATE_PENDING.
	CreatePublicShare(ctx context.Context, in *CreatePublicShareRequest, opts ...grpc.CallOption) (*CreatePublicShareResponse, error)
	// Removes a share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	RemovePublicShare(ctx context.Context, in *RemovePublicShareRequest, opts ...grpc.CallOption) (*RemovePublicShareResponse, error)
	// Gets share information for a single share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	GetPublicShare(ctx context.Context, in *GetPublicShareRequest, opts ...grpc.CallOption) (*GetPublicShareResponse, error)
	// Gets share information for a single share by its unlisted token.
	// MUST return CODE_NOT_FOUND if the share does not exist.
	GetPublicShareByToken(ctx context.Context, in *GetPublicShareByTokenRequest, opts ...grpc.CallOption) (*GetPublicShareByTokenResponse, error)
	// List the shares the authenticated principal has created,
	// both as owner and creator. If a filter is specified, only
	// shares satisfying the filter MUST be returned.
	ListPublicShares(ctx context.Context, in *ListPublicSharesRequest, opts ...grpc.CallOption) (*ListPublicSharesResponse, error)
	// Updates a share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	UpdatePublicShare(ctx context.Context, in *UpdatePublicShareRequest, opts ...grpc.CallOption) (*UpdatePublicShareResponse, error)
}

type linkAPIClient struct {
	cc *grpc.ClientConn
}

func NewLinkAPIClient(cc *grpc.ClientConn) LinkAPIClient {
	return &linkAPIClient{cc}
}

func (c *linkAPIClient) CreatePublicShare(ctx context.Context, in *CreatePublicShareRequest, opts ...grpc.CallOption) (*CreatePublicShareResponse, error) {
	out := new(CreatePublicShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.sharing.link.v1beta1.LinkAPI/CreatePublicShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkAPIClient) RemovePublicShare(ctx context.Context, in *RemovePublicShareRequest, opts ...grpc.CallOption) (*RemovePublicShareResponse, error) {
	out := new(RemovePublicShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.sharing.link.v1beta1.LinkAPI/RemovePublicShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkAPIClient) GetPublicShare(ctx context.Context, in *GetPublicShareRequest, opts ...grpc.CallOption) (*GetPublicShareResponse, error) {
	out := new(GetPublicShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.sharing.link.v1beta1.LinkAPI/GetPublicShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkAPIClient) GetPublicShareByToken(ctx context.Context, in *GetPublicShareByTokenRequest, opts ...grpc.CallOption) (*GetPublicShareByTokenResponse, error) {
	out := new(GetPublicShareByTokenResponse)
	err := c.cc.Invoke(ctx, "/cs3.sharing.link.v1beta1.LinkAPI/GetPublicShareByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkAPIClient) ListPublicShares(ctx context.Context, in *ListPublicSharesRequest, opts ...grpc.CallOption) (*ListPublicSharesResponse, error) {
	out := new(ListPublicSharesResponse)
	err := c.cc.Invoke(ctx, "/cs3.sharing.link.v1beta1.LinkAPI/ListPublicShares", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkAPIClient) UpdatePublicShare(ctx context.Context, in *UpdatePublicShareRequest, opts ...grpc.CallOption) (*UpdatePublicShareResponse, error) {
	out := new(UpdatePublicShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.sharing.link.v1beta1.LinkAPI/UpdatePublicShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkAPIServer is the server API for LinkAPI service.
type LinkAPIServer interface {
	// Creates a new share.
	// MUST return CODE_NOT_FOUND if the resource reference does not exist.
	// MUST return CODE_ALREADY_EXISTS if the share already exists for the 4-tuple consisting of
	// (owner, shared_resource, grantee).
	// New shares MUST be created in the state SHARE_STATE_PENDING.
	CreatePublicShare(context.Context, *CreatePublicShareRequest) (*CreatePublicShareResponse, error)
	// Removes a share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	RemovePublicShare(context.Context, *RemovePublicShareRequest) (*RemovePublicShareResponse, error)
	// Gets share information for a single share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	GetPublicShare(context.Context, *GetPublicShareRequest) (*GetPublicShareResponse, error)
	// Gets share information for a single share by its unlisted token.
	// MUST return CODE_NOT_FOUND if the share does not exist.
	GetPublicShareByToken(context.Context, *GetPublicShareByTokenRequest) (*GetPublicShareByTokenResponse, error)
	// List the shares the authenticated principal has created,
	// both as owner and creator. If a filter is specified, only
	// shares satisfying the filter MUST be returned.
	ListPublicShares(context.Context, *ListPublicSharesRequest) (*ListPublicSharesResponse, error)
	// Updates a share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	UpdatePublicShare(context.Context, *UpdatePublicShareRequest) (*UpdatePublicShareResponse, error)
}

// UnimplementedLinkAPIServer can be embedded to have forward compatible implementations.
type UnimplementedLinkAPIServer struct {
}

func (*UnimplementedLinkAPIServer) CreatePublicShare(ctx context.Context, req *CreatePublicShareRequest) (*CreatePublicShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePublicShare not implemented")
}
func (*UnimplementedLinkAPIServer) RemovePublicShare(ctx context.Context, req *RemovePublicShareRequest) (*RemovePublicShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePublicShare not implemented")
}
func (*UnimplementedLinkAPIServer) GetPublicShare(ctx context.Context, req *GetPublicShareRequest) (*GetPublicShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicShare not implemented")
}
func (*UnimplementedLinkAPIServer) GetPublicShareByToken(ctx context.Context, req *GetPublicShareByTokenRequest) (*GetPublicShareByTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicShareByToken not implemented")
}
func (*UnimplementedLinkAPIServer) ListPublicShares(ctx context.Context, req *ListPublicSharesRequest) (*ListPublicSharesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublicShares not implemented")
}
func (*UnimplementedLinkAPIServer) UpdatePublicShare(ctx context.Context, req *UpdatePublicShareRequest) (*UpdatePublicShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePublicShare not implemented")
}

func RegisterLinkAPIServer(s *grpc.Server, srv LinkAPIServer) {
	s.RegisterService(&_LinkAPI_serviceDesc, srv)
}

func _LinkAPI_CreatePublicShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePublicShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkAPIServer).CreatePublicShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.sharing.link.v1beta1.LinkAPI/CreatePublicShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkAPIServer).CreatePublicShare(ctx, req.(*CreatePublicShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkAPI_RemovePublicShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePublicShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkAPIServer).RemovePublicShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.sharing.link.v1beta1.LinkAPI/RemovePublicShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkAPIServer).RemovePublicShare(ctx, req.(*RemovePublicShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkAPI_GetPublicShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkAPIServer).GetPublicShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.sharing.link.v1beta1.LinkAPI/GetPublicShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkAPIServer).GetPublicShare(ctx, req.(*GetPublicShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkAPI_GetPublicShareByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicShareByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkAPIServer).GetPublicShareByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.sharing.link.v1beta1.LinkAPI/GetPublicShareByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkAPIServer).GetPublicShareByToken(ctx, req.(*GetPublicShareByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkAPI_ListPublicShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkAPIServer).ListPublicShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.sharing.link.v1beta1.LinkAPI/ListPublicShares",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkAPIServer).ListPublicShares(ctx, req.(*ListPublicSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkAPI_UpdatePublicShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePublicShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkAPIServer).UpdatePublicShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.sharing.link.v1beta1.LinkAPI/UpdatePublicShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkAPIServer).UpdatePublicShare(ctx, req.(*UpdatePublicShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LinkAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cs3.sharing.link.v1beta1.LinkAPI",
	HandlerType: (*LinkAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePublicShare",
			Handler:    _LinkAPI_CreatePublicShare_Handler,
		},
		{
			MethodName: "RemovePublicShare",
			Handler:    _LinkAPI_RemovePublicShare_Handler,
		},
		{
			MethodName: "GetPublicShare",
			Handler:    _LinkAPI_GetPublicShare_Handler,
		},
		{
			MethodName: "GetPublicShareByToken",
			Handler:    _LinkAPI_GetPublicShareByToken_Handler,
		},
		{
			MethodName: "ListPublicShares",
			Handler:    _LinkAPI_ListPublicShares_Handler,
		},
		{
			MethodName: "UpdatePublicShare",
			Handler:    _LinkAPI_UpdatePublicShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cs3/sharing/link/v1beta1/link_api.proto",
}
