// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs3/sharing/ocm/v1beta1/resources.proto

package ocmv1beta1

import (
	fmt "fmt"
	v1beta11 "github.com/cs3org/go-cs3apis/cs3/identity/user/v1beta1"
	v1beta1 "github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"
	v1beta12 "github.com/cs3org/go-cs3apis/cs3/types/v1beta1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The state of the share.
type ShareState int32

const (
	// The share is no longer valid, for example, the share expired.
	ShareState_SHARE_STATE_INVALID ShareState = 0
	// New shares MUST be created in the SHARE_STATE_PENDING state.
	// This state means the share is pending to be accepted or rejected
	// by the recipient of the share.
	ShareState_SHARE_STATE_PENDING ShareState = 1
	// The recipient of the share has accepted the share.
	ShareState_SHARE_STATE_ACCEPTED ShareState = 2
	// The recipient of the share has rejected the share.
	// Do not means the share is removed, the recipient MAY
	// change the state to accepted or pending.
	ShareState_SHARE_STATE_REJECTED ShareState = 3
)

var ShareState_name = map[int32]string{
	0: "SHARE_STATE_INVALID",
	1: "SHARE_STATE_PENDING",
	2: "SHARE_STATE_ACCEPTED",
	3: "SHARE_STATE_REJECTED",
}

var ShareState_value = map[string]int32{
	"SHARE_STATE_INVALID":  0,
	"SHARE_STATE_PENDING":  1,
	"SHARE_STATE_ACCEPTED": 2,
	"SHARE_STATE_REJECTED": 3,
}

func (x ShareState) String() string {
	return proto.EnumName(ShareState_name, int32(x))
}

func (ShareState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{0}
}

// Defines the type of share based on its origin.
type Share_ShareType int32

const (
	Share_SHARE_TYPE_INVALID Share_ShareType = 0
	// A regular file or folder share.
	Share_SHARE_TYPE_REGULAR Share_ShareType = 1
	// A file or folder transfer.
	Share_SHARE_TYPE_TRANSFER Share_ShareType = 2
)

var Share_ShareType_name = map[int32]string{
	0: "SHARE_TYPE_INVALID",
	1: "SHARE_TYPE_REGULAR",
	2: "SHARE_TYPE_TRANSFER",
}

var Share_ShareType_value = map[string]int32{
	"SHARE_TYPE_INVALID":  0,
	"SHARE_TYPE_REGULAR":  1,
	"SHARE_TYPE_TRANSFER": 2,
}

func (x Share_ShareType) String() string {
	return proto.EnumName(Share_ShareType_name, int32(x))
}

func (Share_ShareType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{0, 0}
}

// Shares are relationships between a resource owner
// (usually the authenticated user) who grants permissions to a recipient (grantee)
// on a specified resource (reference). UserShares represents both user and groups.
type Share struct {
	// REQUIRED.
	// Opaque unique identifier of the share.
	Id *ShareId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// REQUIRED.
	// Unique identifier of the shared resource (path must be empty).
	Ref *v1beta1.Reference `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	// REQUIRED.
	// Name of the shared resource.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// REQUIRED.
	// Permissions for the grantee to use
	// the resource.
	Permissions *SharePermissions `protobuf:"bytes,4,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// REQUIRED.
	// The receiver of the share, like a user, group ...
	Grantee *v1beta1.Grantee `protobuf:"bytes,5,opt,name=grantee,proto3" json:"grantee,omitempty"`
	// REQUIRED.
	// Uniquely identifies the owner of the share
	// (the resource owner at the time of creating the share).
	// In case the ownership of the underlying resource changes
	// the share owner field MAY change to reflect the change of ownsership.
	Owner *v1beta11.UserId `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	// REQUIRED.
	// Uniquely identifies a principal who initiates the share creation.
	// A creator can create shares on behalf of the owner (because of re-sharing,
	// because belonging to special groups, ...).
	// Creator and owner often result in being the same principal.
	Creator *v1beta11.UserId `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	// REQUIRED.
	// Creation time of the share.
	Ctime *v1beta12.Timestamp `protobuf:"bytes,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// REQUIRED.
	// Last modification time of the share.
	Mtime *v1beta12.Timestamp `protobuf:"bytes,9,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// Specifies the type of the share.
	ShareType            Share_ShareType `protobuf:"varint,10,opt,name=share_type,json=shareType,proto3,enum=cs3.sharing.ocm.v1beta1.Share_ShareType" json:"share_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Share) Reset()         { *m = Share{} }
func (m *Share) String() string { return proto.CompactTextString(m) }
func (*Share) ProtoMessage()    {}
func (*Share) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{0}
}

func (m *Share) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Share.Unmarshal(m, b)
}
func (m *Share) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Share.Marshal(b, m, deterministic)
}
func (m *Share) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Share.Merge(m, src)
}
func (m *Share) XXX_Size() int {
	return xxx_messageInfo_Share.Size(m)
}
func (m *Share) XXX_DiscardUnknown() {
	xxx_messageInfo_Share.DiscardUnknown(m)
}

var xxx_messageInfo_Share proto.InternalMessageInfo

func (m *Share) GetId() *ShareId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Share) GetRef() *v1beta1.Reference {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *Share) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Share) GetPermissions() *SharePermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *Share) GetGrantee() *v1beta1.Grantee {
	if m != nil {
		return m.Grantee
	}
	return nil
}

func (m *Share) GetOwner() *v1beta11.UserId {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Share) GetCreator() *v1beta11.UserId {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Share) GetCtime() *v1beta12.Timestamp {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *Share) GetMtime() *v1beta12.Timestamp {
	if m != nil {
		return m.Mtime
	}
	return nil
}

func (m *Share) GetShareType() Share_ShareType {
	if m != nil {
		return m.ShareType
	}
	return Share_SHARE_TYPE_INVALID
}

// The permissions for a share.
type SharePermissions struct {
	Permissions          *v1beta1.ResourcePermissions `protobuf:"bytes,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Reshare              bool                         `protobuf:"varint,2,opt,name=reshare,proto3" json:"reshare,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SharePermissions) Reset()         { *m = SharePermissions{} }
func (m *SharePermissions) String() string { return proto.CompactTextString(m) }
func (*SharePermissions) ProtoMessage()    {}
func (*SharePermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{1}
}

func (m *SharePermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharePermissions.Unmarshal(m, b)
}
func (m *SharePermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharePermissions.Marshal(b, m, deterministic)
}
func (m *SharePermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharePermissions.Merge(m, src)
}
func (m *SharePermissions) XXX_Size() int {
	return xxx_messageInfo_SharePermissions.Size(m)
}
func (m *SharePermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_SharePermissions.DiscardUnknown(m)
}

var xxx_messageInfo_SharePermissions proto.InternalMessageInfo

func (m *SharePermissions) GetPermissions() *v1beta1.ResourcePermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *SharePermissions) GetReshare() bool {
	if m != nil {
		return m.Reshare
	}
	return false
}

// A received share is the share that a grantee will receive.
// It expands the original share by adding state to the share,
// a display name from the perspective of the grantee and a
// resource mount path in case the share will be mounted
// in a path in a storage provider.
type ReceivedShare struct {
	// REQUIRED.
	Share *Share `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	// REQUIRED.
	// The state of the share.
	State                ShareState `protobuf:"varint,2,opt,name=state,proto3,enum=cs3.sharing.ocm.v1beta1.ShareState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReceivedShare) Reset()         { *m = ReceivedShare{} }
func (m *ReceivedShare) String() string { return proto.CompactTextString(m) }
func (*ReceivedShare) ProtoMessage()    {}
func (*ReceivedShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{2}
}

func (m *ReceivedShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceivedShare.Unmarshal(m, b)
}
func (m *ReceivedShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceivedShare.Marshal(b, m, deterministic)
}
func (m *ReceivedShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivedShare.Merge(m, src)
}
func (m *ReceivedShare) XXX_Size() int {
	return xxx_messageInfo_ReceivedShare.Size(m)
}
func (m *ReceivedShare) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivedShare.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivedShare proto.InternalMessageInfo

func (m *ReceivedShare) GetShare() *Share {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *ReceivedShare) GetState() ShareState {
	if m != nil {
		return m.State
	}
	return ShareState_SHARE_STATE_INVALID
}

// Uniquely identifies a share in the share provider.
// A share MUST be uniquely identify by four (4) elements:
// 1) The share provider id
// 2) The owner of the share
// 3) The resource id
// 4) The grantee for the share
// This 4-tuple MUST be unique.
// For example, owner Alice shares the resource /home/docs with id
// home:1234 to an user named Bob. The 4-tuple will consist of
// 1) The share provider id = "user"
// 2) The owner of the share = "Alice"
// 3) The resource id = "home:1234"
// 4) The grantee for the share = Grantee("type" = "user", "" => "Bob")
type ShareKey struct {
	// REQUIRED.
	Owner *v1beta11.UserId `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// REQUIRED.
	// Unique identifier of the shared resource (path must be empty).
	Ref *v1beta1.Reference `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	// REQUIRED.
	Grantee              *v1beta1.Grantee `protobuf:"bytes,4,opt,name=grantee,proto3" json:"grantee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ShareKey) Reset()         { *m = ShareKey{} }
func (m *ShareKey) String() string { return proto.CompactTextString(m) }
func (*ShareKey) ProtoMessage()    {}
func (*ShareKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{3}
}

func (m *ShareKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareKey.Unmarshal(m, b)
}
func (m *ShareKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareKey.Marshal(b, m, deterministic)
}
func (m *ShareKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareKey.Merge(m, src)
}
func (m *ShareKey) XXX_Size() int {
	return xxx_messageInfo_ShareKey.Size(m)
}
func (m *ShareKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareKey.DiscardUnknown(m)
}

var xxx_messageInfo_ShareKey proto.InternalMessageInfo

func (m *ShareKey) GetOwner() *v1beta11.UserId {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *ShareKey) GetRef() *v1beta1.Reference {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *ShareKey) GetGrantee() *v1beta1.Grantee {
	if m != nil {
		return m.Grantee
	}
	return nil
}

// A share id identifies uniquely a // share in the share provider namespace.
// A ShareId MUST be unique inside the share provider.
type ShareId struct {
	// REQUIRED.
	// The internal id used by service implementor to
	// uniquely identity the share in the internal
	// implementation of the service.
	OpaqueId             string   `protobuf:"bytes,2,opt,name=opaque_id,json=opaqueId,proto3" json:"opaque_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareId) Reset()         { *m = ShareId{} }
func (m *ShareId) String() string { return proto.CompactTextString(m) }
func (*ShareId) ProtoMessage()    {}
func (*ShareId) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{4}
}

func (m *ShareId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareId.Unmarshal(m, b)
}
func (m *ShareId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareId.Marshal(b, m, deterministic)
}
func (m *ShareId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareId.Merge(m, src)
}
func (m *ShareId) XXX_Size() int {
	return xxx_messageInfo_ShareId.Size(m)
}
func (m *ShareId) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareId.DiscardUnknown(m)
}

var xxx_messageInfo_ShareId proto.InternalMessageInfo

func (m *ShareId) GetOpaqueId() string {
	if m != nil {
		return m.OpaqueId
	}
	return ""
}

// The mechanism to identify a share
// in the share provider namespace.
type ShareReference struct {
	// REQUIRED.
	// One of the specifications MUST be specified.
	//
	// Types that are valid to be assigned to Spec:
	//	*ShareReference_Id
	//	*ShareReference_Key
	Spec                 isShareReference_Spec `protobuf_oneof:"spec"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ShareReference) Reset()         { *m = ShareReference{} }
func (m *ShareReference) String() string { return proto.CompactTextString(m) }
func (*ShareReference) ProtoMessage()    {}
func (*ShareReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{5}
}

func (m *ShareReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareReference.Unmarshal(m, b)
}
func (m *ShareReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareReference.Marshal(b, m, deterministic)
}
func (m *ShareReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareReference.Merge(m, src)
}
func (m *ShareReference) XXX_Size() int {
	return xxx_messageInfo_ShareReference.Size(m)
}
func (m *ShareReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareReference.DiscardUnknown(m)
}

var xxx_messageInfo_ShareReference proto.InternalMessageInfo

type isShareReference_Spec interface {
	isShareReference_Spec()
}

type ShareReference_Id struct {
	Id *ShareId `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type ShareReference_Key struct {
	Key *ShareKey `protobuf:"bytes,2,opt,name=key,proto3,oneof"`
}

func (*ShareReference_Id) isShareReference_Spec() {}

func (*ShareReference_Key) isShareReference_Spec() {}

func (m *ShareReference) GetSpec() isShareReference_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ShareReference) GetId() *ShareId {
	if x, ok := m.GetSpec().(*ShareReference_Id); ok {
		return x.Id
	}
	return nil
}

func (m *ShareReference) GetKey() *ShareKey {
	if x, ok := m.GetSpec().(*ShareReference_Key); ok {
		return x.Key
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ShareReference) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ShareReference_Id)(nil),
		(*ShareReference_Key)(nil),
	}
}

// A share grant specifies the share permissions
// for a grantee.
type ShareGrant struct {
	// REQUIRED.
	// The grantee of the grant.
	Grantee *v1beta1.Grantee `protobuf:"bytes,1,opt,name=grantee,proto3" json:"grantee,omitempty"`
	// REQUIRED.
	// The share permissions for the grant.
	Permissions          *SharePermissions `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShareGrant) Reset()         { *m = ShareGrant{} }
func (m *ShareGrant) String() string { return proto.CompactTextString(m) }
func (*ShareGrant) ProtoMessage()    {}
func (*ShareGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b387acee7aaf43, []int{6}
}

func (m *ShareGrant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareGrant.Unmarshal(m, b)
}
func (m *ShareGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareGrant.Marshal(b, m, deterministic)
}
func (m *ShareGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareGrant.Merge(m, src)
}
func (m *ShareGrant) XXX_Size() int {
	return xxx_messageInfo_ShareGrant.Size(m)
}
func (m *ShareGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareGrant.DiscardUnknown(m)
}

var xxx_messageInfo_ShareGrant proto.InternalMessageInfo

func (m *ShareGrant) GetGrantee() *v1beta1.Grantee {
	if m != nil {
		return m.Grantee
	}
	return nil
}

func (m *ShareGrant) GetPermissions() *SharePermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterEnum("cs3.sharing.ocm.v1beta1.ShareState", ShareState_name, ShareState_value)
	proto.RegisterEnum("cs3.sharing.ocm.v1beta1.Share_ShareType", Share_ShareType_name, Share_ShareType_value)
	proto.RegisterType((*Share)(nil), "cs3.sharing.ocm.v1beta1.Share")
	proto.RegisterType((*SharePermissions)(nil), "cs3.sharing.ocm.v1beta1.SharePermissions")
	proto.RegisterType((*ReceivedShare)(nil), "cs3.sharing.ocm.v1beta1.ReceivedShare")
	proto.RegisterType((*ShareKey)(nil), "cs3.sharing.ocm.v1beta1.ShareKey")
	proto.RegisterType((*ShareId)(nil), "cs3.sharing.ocm.v1beta1.ShareId")
	proto.RegisterType((*ShareReference)(nil), "cs3.sharing.ocm.v1beta1.ShareReference")
	proto.RegisterType((*ShareGrant)(nil), "cs3.sharing.ocm.v1beta1.ShareGrant")
}

func init() {
	proto.RegisterFile("cs3/sharing/ocm/v1beta1/resources.proto", fileDescriptor_b8b387acee7aaf43)
}

var fileDescriptor_b8b387acee7aaf43 = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0x41, 0x6f, 0xda, 0x48,
	0x14, 0xc7, 0x63, 0x03, 0x01, 0x5e, 0xb4, 0x08, 0xcd, 0xae, 0x36, 0x56, 0xb2, 0xbb, 0x62, 0xbd,
	0xda, 0x0d, 0x59, 0xad, 0xcc, 0x02, 0xbb, 0xaa, 0xa2, 0x1e, 0x2a, 0x20, 0x2e, 0xa1, 0x89, 0x08,
	0x1a, 0x9c, 0x48, 0xad, 0x22, 0x21, 0xc7, 0x7e, 0x49, 0xac, 0xca, 0xd8, 0x9d, 0x31, 0xa9, 0xb8,
	0xb5, 0xea, 0x47, 0xe8, 0xad, 0xc7, 0x1e, 0xfb, 0x25, 0x7a, 0xef, 0xa7, 0xaa, 0x3c, 0x63, 0x13,
	0x82, 0x04, 0x4d, 0xd2, 0x0b, 0xc2, 0xf3, 0xff, 0xff, 0xc6, 0x6f, 0xde, 0xbc, 0xf7, 0x0c, 0x3b,
	0x0e, 0x6f, 0xd6, 0xf8, 0x95, 0xcd, 0xbc, 0xf1, 0x65, 0x2d, 0x70, 0xfc, 0xda, 0x75, 0xfd, 0x1c,
	0x23, 0xbb, 0x5e, 0x63, 0xc8, 0x83, 0x09, 0x73, 0x90, 0x1b, 0x21, 0x0b, 0xa2, 0x80, 0x6c, 0x3a,
	0xbc, 0x69, 0x24, 0x46, 0x23, 0x70, 0x7c, 0x23, 0x31, 0x6e, 0xed, 0xc6, 0x3b, 0x78, 0x2e, 0x8e,
	0x23, 0x2f, 0x9a, 0xd6, 0x26, 0x1c, 0xd9, 0xb2, 0x3d, 0xb6, 0xfe, 0x11, 0x2f, 0x8b, 0x02, 0x66,
	0x5f, 0x62, 0x2d, 0x64, 0xc1, 0xb5, 0xe7, 0xae, 0x70, 0xff, 0x1a, 0xbb, 0xa3, 0x69, 0x88, 0x7c,
	0x66, 0x11, 0x4f, 0x52, 0xd6, 0xdf, 0xe7, 0x20, 0x37, 0xbc, 0xb2, 0x19, 0x92, 0x7f, 0x41, 0xf5,
	0x5c, 0x4d, 0xa9, 0x28, 0xd5, 0x8d, 0x46, 0xc5, 0x58, 0x12, 0xa7, 0x21, 0xbc, 0x3d, 0x97, 0xaa,
	0x9e, 0x4b, 0xf6, 0x20, 0xc3, 0xf0, 0x42, 0x53, 0x05, 0xb2, 0x23, 0x11, 0x19, 0x96, 0x91, 0x86,
	0x35, 0xe3, 0x28, 0x5e, 0x20, 0xc3, 0xb1, 0x83, 0x34, 0x66, 0x08, 0x81, 0xec, 0xd8, 0xf6, 0x51,
	0xcb, 0x54, 0x94, 0x6a, 0x91, 0x8a, 0xff, 0xe4, 0x10, 0x36, 0x42, 0x64, 0xbe, 0xc7, 0xb9, 0x17,
	0x8c, 0xb9, 0x96, 0x15, 0xdb, 0xee, 0xae, 0x8e, 0x64, 0x70, 0x03, 0xd0, 0x79, 0x9a, 0x3c, 0x81,
	0xfc, 0x25, 0xb3, 0xc7, 0x11, 0xa2, 0x96, 0x13, 0x1b, 0xfd, 0xb9, 0x3a, 0xbe, 0xae, 0x34, 0xd3,
	0x94, 0x22, 0x8f, 0x20, 0x17, 0xbc, 0x1e, 0x23, 0xd3, 0xd6, 0x05, 0xfe, 0xbb, 0xc0, 0xd3, 0x0b,
	0x32, 0xe2, 0x0b, 0x9a, 0xb1, 0x27, 0x1c, 0x59, 0xcf, 0xa5, 0xd2, 0x4f, 0x1e, 0x43, 0xde, 0x61,
	0x68, 0x47, 0x01, 0xd3, 0xf2, 0x77, 0x45, 0x53, 0x82, 0x34, 0x20, 0xe7, 0x44, 0x9e, 0x8f, 0x5a,
	0x41, 0xa0, 0xbf, 0x08, 0x54, 0xde, 0x57, 0x8a, 0x58, 0x9e, 0x8f, 0x3c, 0xb2, 0xfd, 0x90, 0x4a,
	0x6b, 0xcc, 0xf8, 0x82, 0x29, 0xde, 0x85, 0x11, 0x56, 0xd2, 0x05, 0x88, 0x73, 0x8a, 0xa3, 0xd8,
	0xa7, 0x41, 0x45, 0xa9, 0x96, 0x1a, 0xd5, 0xd5, 0xa9, 0x96, 0xbf, 0xd6, 0x34, 0x44, 0x5a, 0xe4,
	0xe9, 0x5f, 0xdd, 0x82, 0xe2, 0x6c, 0x9d, 0xfc, 0x0c, 0x64, 0x78, 0xd0, 0xa2, 0xe6, 0xc8, 0x7a,
	0x3e, 0x30, 0x47, 0xbd, 0xfe, 0x69, 0xeb, 0xa8, 0xb7, 0x5f, 0x5e, 0x5b, 0x58, 0xa7, 0x66, 0xf7,
	0xe4, 0xa8, 0x45, 0xcb, 0x0a, 0xd9, 0x84, 0x1f, 0xe7, 0xd6, 0x2d, 0xda, 0xea, 0x0f, 0x9f, 0x9a,
	0xb4, 0xac, 0xea, 0x6f, 0x15, 0x28, 0x2f, 0xde, 0x2f, 0x19, 0xde, 0xae, 0x0f, 0x59, 0xa9, 0xf5,
	0x6f, 0x95, 0x9d, 0xec, 0x86, 0xa5, 0x75, 0xa2, 0x41, 0x9e, 0xa1, 0x38, 0x8e, 0xa8, 0xe3, 0x02,
	0x4d, 0x1f, 0xf5, 0x37, 0x0a, 0xfc, 0x40, 0xd1, 0x41, 0xef, 0x1a, 0x5d, 0xd9, 0x21, 0xff, 0x41,
	0x4e, 0x3a, 0xe5, 0xab, 0x7f, 0x5b, 0x9d, 0x2f, 0x2a, 0xcd, 0x64, 0x0f, 0x72, 0x3c, 0xb2, 0x23,
	0xb9, 0x7f, 0xa9, 0xf1, 0xc7, 0x6a, 0x6a, 0x18, 0x5b, 0xa9, 0x24, 0xf4, 0xcf, 0x0a, 0x14, 0xc4,
	0xea, 0x21, 0x4e, 0x6f, 0x0a, 0x52, 0xbd, 0x67, 0x41, 0x26, 0x6d, 0x9a, 0x79, 0x40, 0x9b, 0xce,
	0x75, 0x51, 0xf6, 0x21, 0x5d, 0xa4, 0xff, 0x05, 0xf9, 0x64, 0x62, 0x90, 0x6d, 0x28, 0x06, 0xa1,
	0xfd, 0x6a, 0x82, 0x23, 0xcf, 0x15, 0x67, 0x28, 0xd2, 0x82, 0x5c, 0xe8, 0xb9, 0xfa, 0x3b, 0x05,
	0x4a, 0x32, 0x6b, 0x69, 0x00, 0xa4, 0x71, 0x9f, 0x79, 0x74, 0xb0, 0x26, 0x26, 0xd2, 0xff, 0x90,
	0x79, 0x89, 0xd3, 0x5b, 0x19, 0x5a, 0x0a, 0x1d, 0xe2, 0xf4, 0x60, 0x8d, 0xc6, 0xfe, 0xf6, 0x3a,
	0x64, 0x79, 0x88, 0x8e, 0xfe, 0x41, 0x01, 0x10, 0x9a, 0x38, 0xc7, 0xfc, 0xe9, 0x95, 0x07, 0xcd,
	0x90, 0x85, 0x89, 0xa6, 0x7e, 0xcf, 0x44, 0xfb, 0x9b, 0x25, 0xb1, 0x89, 0x0a, 0xb9, 0x69, 0x9d,
	0xa1, 0xd5, 0xb2, 0xe6, 0x7b, 0x6d, 0x41, 0x18, 0x98, 0xfd, 0xfd, 0x5e, 0xbf, 0x5b, 0x56, 0x88,
	0x06, 0x3f, 0xcd, 0x0b, 0xad, 0x4e, 0xc7, 0x1c, 0x58, 0xe6, 0x7e, 0x59, 0x5d, 0x54, 0xa8, 0xf9,
	0xcc, 0xec, 0xc4, 0x4a, 0xa6, 0x3d, 0x81, 0x6d, 0x27, 0xf0, 0x97, 0x05, 0xdc, 0x2e, 0xa5, 0xed,
	0xc5, 0x07, 0xf1, 0xc7, 0x64, 0xa0, 0xbc, 0x80, 0xc0, 0xf1, 0x13, 0xf5, 0xa3, 0x9a, 0xe9, 0x0c,
	0x8f, 0x3f, 0xa9, 0x9b, 0x1d, 0xde, 0x14, 0x47, 0x8b, 0xe9, 0x63, 0xc7, 0x37, 0x4e, 0xeb, 0xed,
	0x58, 0xff, 0x22, 0x94, 0xb3, 0x44, 0x39, 0x3b, 0x76, 0xfc, 0xb3, 0x44, 0x39, 0x5f, 0x17, 0xdf,
	0xa6, 0xe6, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0xb2, 0xba, 0x0b, 0x57, 0x07, 0x00, 0x00,
}
