// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs3/storage/provider/v1beta1/resources.proto

package providerv1beta1

import (
	fmt "fmt"
	v1beta12 "github.com/cs3org/go-cs3apis/cs3/identity/group/v1beta1"
	v1beta11 "github.com/cs3org/go-cs3apis/cs3/identity/user/v1beta1"
	v1beta1 "github.com/cs3org/go-cs3apis/cs3/types/v1beta1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The available types of resources.
type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_INVALID ResourceType = 0
	// The file type represents a type
	// that holds arbitrary data.
	// Service implementors usually map this type
	// to files (local filesystem) or objects
	// (Amazon S3).
	ResourceType_RESOURCE_TYPE_FILE ResourceType = 1
	// The container type represents a type
	// that can contain another types.
	// Service implementors usually map this type
	// to folders (local filesystem) or buckets
	// (Amazon S3).
	ResourceType_RESOURCE_TYPE_CONTAINER ResourceType = 2
	// This represents a reference type which points
	// to another resource where client MAY be redirected.
	// Client SHOULD use the ResourceInfo.target
	// reference for a subsequent call.
	ResourceType_RESOURCE_TYPE_REFERENCE ResourceType = 3
	// This represents a symbolic link type if the underlying
	// storage system supports it.
	// Symlink target SHOULD NOT be interpreted by the clients.
	ResourceType_RESOURCE_TYPE_SYMLINK ResourceType = 4
	// Internal resource type for some specific resources inside
	// a storage implementation.
	// For example, this type could be used to represent
	// a device file on a Linux filesystem.
	// Another example could be to represent an ongoing upload,
	// where an hypothetically user interface could show a loading icon
	// on this type of resources until the upload operation is completed.
	// Internal resources SHOULD NOT be moved to a different storage
	// provider.
	ResourceType_RESOURCE_TYPE_INTERNAL ResourceType = 5
)

var ResourceType_name = map[int32]string{
	0: "RESOURCE_TYPE_INVALID",
	1: "RESOURCE_TYPE_FILE",
	2: "RESOURCE_TYPE_CONTAINER",
	3: "RESOURCE_TYPE_REFERENCE",
	4: "RESOURCE_TYPE_SYMLINK",
	5: "RESOURCE_TYPE_INTERNAL",
}

var ResourceType_value = map[string]int32{
	"RESOURCE_TYPE_INVALID":   0,
	"RESOURCE_TYPE_FILE":      1,
	"RESOURCE_TYPE_CONTAINER": 2,
	"RESOURCE_TYPE_REFERENCE": 3,
	"RESOURCE_TYPE_SYMLINK":   4,
	"RESOURCE_TYPE_INTERNAL":  5,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}

func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{0}
}

// The type of checksum to use.
type ResourceChecksumType int32

const (
	ResourceChecksumType_RESOURCE_CHECKSUM_TYPE_INVALID ResourceChecksumType = 0
	// unset means no checksum is set.
	ResourceChecksumType_RESOURCE_CHECKSUM_TYPE_UNSET ResourceChecksumType = 1
	// Use Adler32 checksum.
	ResourceChecksumType_RESOURCE_CHECKSUM_TYPE_ADLER32 ResourceChecksumType = 2
	// Use MD5 checksum.
	ResourceChecksumType_RESOURCE_CHECKSUM_TYPE_MD5 ResourceChecksumType = 3
	// Use SHA-1 checksum.
	ResourceChecksumType_RESOURCE_CHECKSUM_TYPE_SHA1 ResourceChecksumType = 4
)

var ResourceChecksumType_name = map[int32]string{
	0: "RESOURCE_CHECKSUM_TYPE_INVALID",
	1: "RESOURCE_CHECKSUM_TYPE_UNSET",
	2: "RESOURCE_CHECKSUM_TYPE_ADLER32",
	3: "RESOURCE_CHECKSUM_TYPE_MD5",
	4: "RESOURCE_CHECKSUM_TYPE_SHA1",
}

var ResourceChecksumType_value = map[string]int32{
	"RESOURCE_CHECKSUM_TYPE_INVALID": 0,
	"RESOURCE_CHECKSUM_TYPE_UNSET":   1,
	"RESOURCE_CHECKSUM_TYPE_ADLER32": 2,
	"RESOURCE_CHECKSUM_TYPE_MD5":     3,
	"RESOURCE_CHECKSUM_TYPE_SHA1":    4,
}

func (x ResourceChecksumType) String() string {
	return proto.EnumName(ResourceChecksumType_name, int32(x))
}

func (ResourceChecksumType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{1}
}

// The type of the grantee.
type GranteeType int32

const (
	GranteeType_GRANTEE_TYPE_INVALID GranteeType = 0
	// This type represents an individual.
	GranteeType_GRANTEE_TYPE_USER GranteeType = 1
	// This type represents a group of individuals.
	GranteeType_GRANTEE_TYPE_GROUP GranteeType = 2
)

var GranteeType_name = map[int32]string{
	0: "GRANTEE_TYPE_INVALID",
	1: "GRANTEE_TYPE_USER",
	2: "GRANTEE_TYPE_GROUP",
}

var GranteeType_value = map[string]int32{
	"GRANTEE_TYPE_INVALID": 0,
	"GRANTEE_TYPE_USER":    1,
	"GRANTEE_TYPE_GROUP":   2,
}

func (x GranteeType) String() string {
	return proto.EnumName(GranteeType_name, int32(x))
}

func (GranteeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{2}
}

// Represents the information (metadata) about
// a storage resource organized in a hierarchical namespace (file, directory/container, reference, symlink, ...).
type ResourceInfo struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The type of the resource (container, file, ...)
	// See the enum ResourceType for all possible types.
	Type ResourceType `protobuf:"varint,2,opt,name=type,proto3,enum=cs3.storage.provider.v1beta1.ResourceType" json:"type,omitempty"`
	// REQUIRED.
	// Opaque unique identifier of the resource.
	Id *Reference `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// REQUIRED.
	// The data checksum for the file resource.
	// For all other resources, the checksum is unset.
	Checksum *ResourceChecksum `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// REQUIRED.
	// As decribed in https://tools.ietf.org/html/rfc7232#section-2.3
	// For file resources, the etag must change if data or metadata changes.
	// For container types, the etag must change if etag of any of the (indirectly) contained resources change.
	// For reference types, the etag must change if etag of the target changes and the target is on the same storage provider.
	// In all other cases the etag does not change.
	Etag string `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	// REQUIRED.
	// As described in [RFC 2015](https://tools.ietf.org/html/rfc2045#page-7)
	MimeType string `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// REQUIRED.
	// Last modification time (mtime) of file or directory contents.
	// For reference types this is NOT the mtime of the target.
	Mtime *v1beta1.Timestamp `protobuf:"bytes,7,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// REQUIRED.
	// The reference for the resource.
	Ref *Reference `protobuf:"bytes,8,opt,name=ref,proto3" json:"ref,omitempty"`
	// REQUIRED.
	// The set of permissions for the resource effective for the authenticated user.
	PermissionSet *ResourcePermissions `protobuf:"bytes,9,opt,name=permission_set,json=permissionSet,proto3" json:"permission_set,omitempty"`
	// REQUIRED.
	// The size of the resource in bytes (file size)
	// TODO(moscicki): This is undefined for container type.
	// Is the accounting recursive?, could it be set to 0 for directories if recursive not supported? use another field?
	// TODO(moscicki): This needs to be defined also for other types (such as a symlink to a directory or file)
	Size uint64 `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
	// REQUIRED:
	// Identifier of the owner of the resource.
	Owner *v1beta11.UserId `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	// REQUIRED if ResourceType is either RESOURCE_TYPE_SYMLINK or RESOURCE_TYPE_REFERENCE
	Target string `protobuf:"bytes,12,opt,name=target,proto3" json:"target,omitempty"`
	// OPTIONAL.
	// Additional metadata attached to the resource.
	// If resource type is RESOURCE_TYPE_REFERENCE it MUST
	// be specified.
	CanonicalMetadata *CanonicalMetadata `protobuf:"bytes,13,opt,name=canonical_metadata,json=canonicalMetadata,proto3" json:"canonical_metadata,omitempty"`
	// OPTIONAL.
	// Arbitrary metadata attached to a resource.
	ArbitraryMetadata    *ArbitraryMetadata `protobuf:"bytes,14,opt,name=arbitrary_metadata,json=arbitraryMetadata,proto3" json:"arbitrary_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ResourceInfo) Reset()         { *m = ResourceInfo{} }
func (m *ResourceInfo) String() string { return proto.CompactTextString(m) }
func (*ResourceInfo) ProtoMessage()    {}
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{0}
}

func (m *ResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceInfo.Unmarshal(m, b)
}
func (m *ResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceInfo.Marshal(b, m, deterministic)
}
func (m *ResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceInfo.Merge(m, src)
}
func (m *ResourceInfo) XXX_Size() int {
	return xxx_messageInfo_ResourceInfo.Size(m)
}
func (m *ResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceInfo proto.InternalMessageInfo

func (m *ResourceInfo) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *ResourceInfo) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_RESOURCE_TYPE_INVALID
}

func (m *ResourceInfo) GetId() *Reference {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ResourceInfo) GetChecksum() *ResourceChecksum {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *ResourceInfo) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *ResourceInfo) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *ResourceInfo) GetMtime() *v1beta1.Timestamp {
	if m != nil {
		return m.Mtime
	}
	return nil
}

func (m *ResourceInfo) GetRef() *Reference {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *ResourceInfo) GetPermissionSet() *ResourcePermissions {
	if m != nil {
		return m.PermissionSet
	}
	return nil
}

func (m *ResourceInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ResourceInfo) GetOwner() *v1beta11.UserId {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *ResourceInfo) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ResourceInfo) GetCanonicalMetadata() *CanonicalMetadata {
	if m != nil {
		return m.CanonicalMetadata
	}
	return nil
}

func (m *ResourceInfo) GetArbitraryMetadata() *ArbitraryMetadata {
	if m != nil {
		return m.ArbitraryMetadata
	}
	return nil
}

// CanonicalMetadata contains extra metadata
// attached to a resource. This message and the Opaque
// message differ in that Opaque allows service implementors
// to include any extra metadata in any format and most clients
// will ignore it. However, the CanonicalMetadata message
// contains well defined fileds that clients MUST understand if
// they are specified.
type CanonicalMetadata struct {
	// REQUIRED if resource type is RESOURCE_TYPE_REFERENCE.
	// The target reference the resource points to.
	Target               *Reference `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CanonicalMetadata) Reset()         { *m = CanonicalMetadata{} }
func (m *CanonicalMetadata) String() string { return proto.CompactTextString(m) }
func (*CanonicalMetadata) ProtoMessage()    {}
func (*CanonicalMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{1}
}

func (m *CanonicalMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanonicalMetadata.Unmarshal(m, b)
}
func (m *CanonicalMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanonicalMetadata.Marshal(b, m, deterministic)
}
func (m *CanonicalMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanonicalMetadata.Merge(m, src)
}
func (m *CanonicalMetadata) XXX_Size() int {
	return xxx_messageInfo_CanonicalMetadata.Size(m)
}
func (m *CanonicalMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CanonicalMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CanonicalMetadata proto.InternalMessageInfo

func (m *CanonicalMetadata) GetTarget() *Reference {
	if m != nil {
		return m.Target
	}
	return nil
}

// Arbitrary metadata than can be set to the resource.
type ArbitraryMetadata struct {
	Metadata             map[string]string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ArbitraryMetadata) Reset()         { *m = ArbitraryMetadata{} }
func (m *ArbitraryMetadata) String() string { return proto.CompactTextString(m) }
func (*ArbitraryMetadata) ProtoMessage()    {}
func (*ArbitraryMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{2}
}

func (m *ArbitraryMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArbitraryMetadata.Unmarshal(m, b)
}
func (m *ArbitraryMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArbitraryMetadata.Marshal(b, m, deterministic)
}
func (m *ArbitraryMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArbitraryMetadata.Merge(m, src)
}
func (m *ArbitraryMetadata) XXX_Size() int {
	return xxx_messageInfo_ArbitraryMetadata.Size(m)
}
func (m *ArbitraryMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ArbitraryMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ArbitraryMetadata proto.InternalMessageInfo

func (m *ArbitraryMetadata) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// The checksum to verify
// the integrity of a resource.
type ResourceChecksum struct {
	// REQUIRED.
	// The type of checksum to use.
	// If no checksum is provided,
	// type MUST be RESOURCE_CHECKSUM_TYPE_UNSET.
	Type ResourceChecksumType `protobuf:"varint,1,opt,name=type,proto3,enum=cs3.storage.provider.v1beta1.ResourceChecksumType" json:"type,omitempty"`
	// MUST be specified if type is not
	// RESOURCE_CHECKSUM_TYPE_UNSET or type is not
	// RESOURCE_CHECKSUM_TYPE_INVALID.
	// MUST be the hexadecimal representation of the cheksum.
	// The value is case-insensitive, so
	// "1E603A8", "1e603a8" or "1e603A8" are the same.
	Sum                  string   `protobuf:"bytes,2,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceChecksum) Reset()         { *m = ResourceChecksum{} }
func (m *ResourceChecksum) String() string { return proto.CompactTextString(m) }
func (*ResourceChecksum) ProtoMessage()    {}
func (*ResourceChecksum) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{3}
}

func (m *ResourceChecksum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceChecksum.Unmarshal(m, b)
}
func (m *ResourceChecksum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceChecksum.Marshal(b, m, deterministic)
}
func (m *ResourceChecksum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceChecksum.Merge(m, src)
}
func (m *ResourceChecksum) XXX_Size() int {
	return xxx_messageInfo_ResourceChecksum.Size(m)
}
func (m *ResourceChecksum) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceChecksum.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceChecksum proto.InternalMessageInfo

func (m *ResourceChecksum) GetType() ResourceChecksumType {
	if m != nil {
		return m.Type
	}
	return ResourceChecksumType_RESOURCE_CHECKSUM_TYPE_INVALID
}

func (m *ResourceChecksum) GetSum() string {
	if m != nil {
		return m.Sum
	}
	return ""
}

// When negotiating the user of checksum types
// between client and server, this structure
// defines the priority of the checksum.
// Priority 0 means highest priority.
type ResourceChecksumPriority struct {
	Type                 ResourceChecksumType `protobuf:"varint,1,opt,name=type,proto3,enum=cs3.storage.provider.v1beta1.ResourceChecksumType" json:"type,omitempty"`
	Priority             uint32               `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResourceChecksumPriority) Reset()         { *m = ResourceChecksumPriority{} }
func (m *ResourceChecksumPriority) String() string { return proto.CompactTextString(m) }
func (*ResourceChecksumPriority) ProtoMessage()    {}
func (*ResourceChecksumPriority) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{4}
}

func (m *ResourceChecksumPriority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceChecksumPriority.Unmarshal(m, b)
}
func (m *ResourceChecksumPriority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceChecksumPriority.Marshal(b, m, deterministic)
}
func (m *ResourceChecksumPriority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceChecksumPriority.Merge(m, src)
}
func (m *ResourceChecksumPriority) XXX_Size() int {
	return xxx_messageInfo_ResourceChecksumPriority.Size(m)
}
func (m *ResourceChecksumPriority) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceChecksumPriority.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceChecksumPriority proto.InternalMessageInfo

func (m *ResourceChecksumPriority) GetType() ResourceChecksumType {
	if m != nil {
		return m.Type
	}
	return ResourceChecksumType_RESOURCE_CHECKSUM_TYPE_INVALID
}

func (m *ResourceChecksumPriority) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

// The mechanism to identify a resource in the CS3 namespace.
// It can represent path based, id based and combined references:
// The storage registry uses the storage_id to determine the responsible storage provider.
// When the storage_id is not available it will use the path.
// In a URL the different components can be represented in a string using the following layout:
// <storage_id>!<node_id>:<path>
type Reference struct {
	// OPTIONAL.
	// The logical id of a storage. Used by the storage registry to determine the responsible storage provider.
	StorageId string `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	// OPTIONAL.
	// The logical node id used by a storage provider to uniquely identify a resource in a storage.
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// OPTIONAL.
	// When starting with `/` the reference represents an absolute path. In this case the storage_id and the node_id must be empty.
	// When not starting with `/` represents a path relative to the node_id.
	// When node_id is empty the path is considered relative to the root of the storage.
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reference) Reset()         { *m = Reference{} }
func (m *Reference) String() string { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()    {}
func (*Reference) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{5}
}

func (m *Reference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference.Unmarshal(m, b)
}
func (m *Reference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference.Marshal(b, m, deterministic)
}
func (m *Reference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference.Merge(m, src)
}
func (m *Reference) XXX_Size() int {
	return xxx_messageInfo_Reference.Size(m)
}
func (m *Reference) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference.DiscardUnknown(m)
}

var xxx_messageInfo_Reference proto.InternalMessageInfo

func (m *Reference) GetStorageId() string {
	if m != nil {
		return m.StorageId
	}
	return ""
}

func (m *Reference) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Reference) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// The representation of permissions attached to a resource.
type ResourcePermissions struct {
	AddGrant             bool     `protobuf:"varint,1,opt,name=add_grant,json=addGrant,proto3" json:"add_grant,omitempty"`
	CreateContainer      bool     `protobuf:"varint,2,opt,name=create_container,json=createContainer,proto3" json:"create_container,omitempty"`
	Delete               bool     `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	GetPath              bool     `protobuf:"varint,5,opt,name=get_path,json=getPath,proto3" json:"get_path,omitempty"`
	GetQuota             bool     `protobuf:"varint,6,opt,name=get_quota,json=getQuota,proto3" json:"get_quota,omitempty"`
	InitiateFileDownload bool     `protobuf:"varint,7,opt,name=initiate_file_download,json=initiateFileDownload,proto3" json:"initiate_file_download,omitempty"`
	InitiateFileUpload   bool     `protobuf:"varint,8,opt,name=initiate_file_upload,json=initiateFileUpload,proto3" json:"initiate_file_upload,omitempty"`
	ListGrants           bool     `protobuf:"varint,9,opt,name=list_grants,json=listGrants,proto3" json:"list_grants,omitempty"`
	ListContainer        bool     `protobuf:"varint,10,opt,name=list_container,json=listContainer,proto3" json:"list_container,omitempty"`
	ListFileVersions     bool     `protobuf:"varint,11,opt,name=list_file_versions,json=listFileVersions,proto3" json:"list_file_versions,omitempty"`
	ListRecycle          bool     `protobuf:"varint,12,opt,name=list_recycle,json=listRecycle,proto3" json:"list_recycle,omitempty"`
	Move                 bool     `protobuf:"varint,13,opt,name=move,proto3" json:"move,omitempty"`
	RemoveGrant          bool     `protobuf:"varint,14,opt,name=remove_grant,json=removeGrant,proto3" json:"remove_grant,omitempty"`
	PurgeRecycle         bool     `protobuf:"varint,15,opt,name=purge_recycle,json=purgeRecycle,proto3" json:"purge_recycle,omitempty"`
	RestoreFileVersion   bool     `protobuf:"varint,16,opt,name=restore_file_version,json=restoreFileVersion,proto3" json:"restore_file_version,omitempty"`
	RestoreRecycleItem   bool     `protobuf:"varint,17,opt,name=restore_recycle_item,json=restoreRecycleItem,proto3" json:"restore_recycle_item,omitempty"`
	Stat                 bool     `protobuf:"varint,18,opt,name=stat,proto3" json:"stat,omitempty"`
	UpdateGrant          bool     `protobuf:"varint,19,opt,name=update_grant,json=updateGrant,proto3" json:"update_grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcePermissions) Reset()         { *m = ResourcePermissions{} }
func (m *ResourcePermissions) String() string { return proto.CompactTextString(m) }
func (*ResourcePermissions) ProtoMessage()    {}
func (*ResourcePermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{6}
}

func (m *ResourcePermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcePermissions.Unmarshal(m, b)
}
func (m *ResourcePermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcePermissions.Marshal(b, m, deterministic)
}
func (m *ResourcePermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcePermissions.Merge(m, src)
}
func (m *ResourcePermissions) XXX_Size() int {
	return xxx_messageInfo_ResourcePermissions.Size(m)
}
func (m *ResourcePermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcePermissions.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcePermissions proto.InternalMessageInfo

func (m *ResourcePermissions) GetAddGrant() bool {
	if m != nil {
		return m.AddGrant
	}
	return false
}

func (m *ResourcePermissions) GetCreateContainer() bool {
	if m != nil {
		return m.CreateContainer
	}
	return false
}

func (m *ResourcePermissions) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

func (m *ResourcePermissions) GetGetPath() bool {
	if m != nil {
		return m.GetPath
	}
	return false
}

func (m *ResourcePermissions) GetGetQuota() bool {
	if m != nil {
		return m.GetQuota
	}
	return false
}

func (m *ResourcePermissions) GetInitiateFileDownload() bool {
	if m != nil {
		return m.InitiateFileDownload
	}
	return false
}

func (m *ResourcePermissions) GetInitiateFileUpload() bool {
	if m != nil {
		return m.InitiateFileUpload
	}
	return false
}

func (m *ResourcePermissions) GetListGrants() bool {
	if m != nil {
		return m.ListGrants
	}
	return false
}

func (m *ResourcePermissions) GetListContainer() bool {
	if m != nil {
		return m.ListContainer
	}
	return false
}

func (m *ResourcePermissions) GetListFileVersions() bool {
	if m != nil {
		return m.ListFileVersions
	}
	return false
}

func (m *ResourcePermissions) GetListRecycle() bool {
	if m != nil {
		return m.ListRecycle
	}
	return false
}

func (m *ResourcePermissions) GetMove() bool {
	if m != nil {
		return m.Move
	}
	return false
}

func (m *ResourcePermissions) GetRemoveGrant() bool {
	if m != nil {
		return m.RemoveGrant
	}
	return false
}

func (m *ResourcePermissions) GetPurgeRecycle() bool {
	if m != nil {
		return m.PurgeRecycle
	}
	return false
}

func (m *ResourcePermissions) GetRestoreFileVersion() bool {
	if m != nil {
		return m.RestoreFileVersion
	}
	return false
}

func (m *ResourcePermissions) GetRestoreRecycleItem() bool {
	if m != nil {
		return m.RestoreRecycleItem
	}
	return false
}

func (m *ResourcePermissions) GetStat() bool {
	if m != nil {
		return m.Stat
	}
	return false
}

func (m *ResourcePermissions) GetUpdateGrant() bool {
	if m != nil {
		return m.UpdateGrant
	}
	return false
}

// A grant grants permissions
// to a resource to a grantee.
type Grant struct {
	// REQUIRED.
	// The grantee of the grant.
	Grantee *Grantee `protobuf:"bytes,1,opt,name=grantee,proto3" json:"grantee,omitempty"`
	// REQUIRED.
	// The permissions for the grant.
	Permissions          *ResourcePermissions `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Grant) Reset()         { *m = Grant{} }
func (m *Grant) String() string { return proto.CompactTextString(m) }
func (*Grant) ProtoMessage()    {}
func (*Grant) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{7}
}

func (m *Grant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grant.Unmarshal(m, b)
}
func (m *Grant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grant.Marshal(b, m, deterministic)
}
func (m *Grant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grant.Merge(m, src)
}
func (m *Grant) XXX_Size() int {
	return xxx_messageInfo_Grant.Size(m)
}
func (m *Grant) XXX_DiscardUnknown() {
	xxx_messageInfo_Grant.DiscardUnknown(m)
}

var xxx_messageInfo_Grant proto.InternalMessageInfo

func (m *Grant) GetGrantee() *Grantee {
	if m != nil {
		return m.Grantee
	}
	return nil
}

func (m *Grant) GetPermissions() *ResourcePermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

// A grantee is the receiver of a grant.
type Grantee struct {
	// REQUIRED.
	// The type of the grantee.
	Type GranteeType `protobuf:"varint,1,opt,name=type,proto3,enum=cs3.storage.provider.v1beta1.GranteeType" json:"type,omitempty"`
	// REQUIRED.
	// The unique id for the grantee.
	// One of the ids MUST be specified.
	//
	// Types that are valid to be assigned to Id:
	//	*Grantee_UserId
	//	*Grantee_GroupId
	Id isGrantee_Id `protobuf_oneof:"id"`
	// OPTIONAL.
	// Opaque information such as UID or GID.
	Opaque               *v1beta1.Opaque `protobuf:"bytes,5,opt,name=opaque,proto3" json:"opaque,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Grantee) Reset()         { *m = Grantee{} }
func (m *Grantee) String() string { return proto.CompactTextString(m) }
func (*Grantee) ProtoMessage()    {}
func (*Grantee) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{8}
}

func (m *Grantee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grantee.Unmarshal(m, b)
}
func (m *Grantee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grantee.Marshal(b, m, deterministic)
}
func (m *Grantee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grantee.Merge(m, src)
}
func (m *Grantee) XXX_Size() int {
	return xxx_messageInfo_Grantee.Size(m)
}
func (m *Grantee) XXX_DiscardUnknown() {
	xxx_messageInfo_Grantee.DiscardUnknown(m)
}

var xxx_messageInfo_Grantee proto.InternalMessageInfo

func (m *Grantee) GetType() GranteeType {
	if m != nil {
		return m.Type
	}
	return GranteeType_GRANTEE_TYPE_INVALID
}

type isGrantee_Id interface {
	isGrantee_Id()
}

type Grantee_UserId struct {
	UserId *v1beta11.UserId `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof"`
}

type Grantee_GroupId struct {
	GroupId *v1beta12.GroupId `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3,oneof"`
}

func (*Grantee_UserId) isGrantee_Id() {}

func (*Grantee_GroupId) isGrantee_Id() {}

func (m *Grantee) GetId() isGrantee_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Grantee) GetUserId() *v1beta11.UserId {
	if x, ok := m.GetId().(*Grantee_UserId); ok {
		return x.UserId
	}
	return nil
}

func (m *Grantee) GetGroupId() *v1beta12.GroupId {
	if x, ok := m.GetId().(*Grantee_GroupId); ok {
		return x.GroupId
	}
	return nil
}

func (m *Grantee) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Grantee) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Grantee_UserId)(nil),
		(*Grantee_GroupId)(nil),
	}
}

// The information for a file version.
// TODO(labkode): make size and mtime OPTIONAL?
type FileVersion struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// MUST the specified.
	// The key to identify the version.
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// REQUIRED.
	// The size in bytes of the file version.
	Size uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// REQUIRED.
	// The Unix Epoch timestamp in seconds.
	Mtime uint64 `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// REQUIRED.
	// As decribed in https://tools.ietf.org/html/rfc7232#section-2.3
	// For a file version, the etag does not change because a version is immutable.
	Etag                 string   `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileVersion) Reset()         { *m = FileVersion{} }
func (m *FileVersion) String() string { return proto.CompactTextString(m) }
func (*FileVersion) ProtoMessage()    {}
func (*FileVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{9}
}

func (m *FileVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileVersion.Unmarshal(m, b)
}
func (m *FileVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileVersion.Marshal(b, m, deterministic)
}
func (m *FileVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileVersion.Merge(m, src)
}
func (m *FileVersion) XXX_Size() int {
	return xxx_messageInfo_FileVersion.Size(m)
}
func (m *FileVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_FileVersion.DiscardUnknown(m)
}

var xxx_messageInfo_FileVersion proto.InternalMessageInfo

func (m *FileVersion) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *FileVersion) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FileVersion) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileVersion) GetMtime() uint64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *FileVersion) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

// A recycle item represents the information
// of a deleted resource.
type RecycleItem struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The type of the resource.
	Type ResourceType `protobuf:"varint,2,opt,name=type,proto3,enum=cs3.storage.provider.v1beta1.ResourceType" json:"type,omitempty"`
	// REQUIRED.
	// The key to identify the deleted resource.
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// REQUIRED.
	// The original reference of the deleted resource.
	Ref *Reference `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"`
	// OPTIONAL.
	// The size of the deleted resource.
	Size uint64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// REQUIRED.
	// The deletion time of the resource
	// in Unix Epoch timestamp in seconds.
	DeletionTime         *v1beta1.Timestamp `protobuf:"bytes,6,opt,name=deletion_time,json=deletionTime,proto3" json:"deletion_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RecycleItem) Reset()         { *m = RecycleItem{} }
func (m *RecycleItem) String() string { return proto.CompactTextString(m) }
func (*RecycleItem) ProtoMessage()    {}
func (*RecycleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{10}
}

func (m *RecycleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecycleItem.Unmarshal(m, b)
}
func (m *RecycleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecycleItem.Marshal(b, m, deterministic)
}
func (m *RecycleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecycleItem.Merge(m, src)
}
func (m *RecycleItem) XXX_Size() int {
	return xxx_messageInfo_RecycleItem.Size(m)
}
func (m *RecycleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RecycleItem.DiscardUnknown(m)
}

var xxx_messageInfo_RecycleItem proto.InternalMessageInfo

func (m *RecycleItem) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *RecycleItem) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_RESOURCE_TYPE_INVALID
}

func (m *RecycleItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RecycleItem) GetRef() *Reference {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *RecycleItem) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RecycleItem) GetDeletionTime() *v1beta1.Timestamp {
	if m != nil {
		return m.DeletionTime
	}
	return nil
}

// A file upload protocol object stores information about
// uploading resources using a specific protocol.
type FileUploadProtocol struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The protocol to be followed.
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// REQUIRED.
	// The endpoint where to upload the data.
	// The value MUST be a Uniform Resource Identifier (URI)
	// as specified in RFC 3986.
	UploadEndpoint string `protobuf:"bytes,3,opt,name=upload_endpoint,json=uploadEndpoint,proto3" json:"upload_endpoint,omitempty"`
	// REQUIRED.
	// List of available checksums
	// the client can use when sending
	// the file.
	AvailableChecksums []*ResourceChecksumPriority `protobuf:"bytes,4,rep,name=available_checksums,json=availableChecksums,proto3" json:"available_checksums,omitempty"`
	// REQUIRED.
	// Tells to the gateway if the client should be exposed directly to the upload_endpoint.
	Expose               bool     `protobuf:"varint,5,opt,name=expose,proto3" json:"expose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileUploadProtocol) Reset()         { *m = FileUploadProtocol{} }
func (m *FileUploadProtocol) String() string { return proto.CompactTextString(m) }
func (*FileUploadProtocol) ProtoMessage()    {}
func (*FileUploadProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{11}
}

func (m *FileUploadProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileUploadProtocol.Unmarshal(m, b)
}
func (m *FileUploadProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileUploadProtocol.Marshal(b, m, deterministic)
}
func (m *FileUploadProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileUploadProtocol.Merge(m, src)
}
func (m *FileUploadProtocol) XXX_Size() int {
	return xxx_messageInfo_FileUploadProtocol.Size(m)
}
func (m *FileUploadProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_FileUploadProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_FileUploadProtocol proto.InternalMessageInfo

func (m *FileUploadProtocol) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *FileUploadProtocol) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *FileUploadProtocol) GetUploadEndpoint() string {
	if m != nil {
		return m.UploadEndpoint
	}
	return ""
}

func (m *FileUploadProtocol) GetAvailableChecksums() []*ResourceChecksumPriority {
	if m != nil {
		return m.AvailableChecksums
	}
	return nil
}

func (m *FileUploadProtocol) GetExpose() bool {
	if m != nil {
		return m.Expose
	}
	return false
}

// A file download protocol object stores information about
// downloading resources using a specific protocol.
type FileDownloadProtocol struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The protocol to be followed.
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// REQUIRED.
	// The endpoint where to download the data.
	// The value MUST be a Uniform Resource Identifier (URI)
	// as specified in RFC 3986.
	DownloadEndpoint string `protobuf:"bytes,3,opt,name=download_endpoint,json=downloadEndpoint,proto3" json:"download_endpoint,omitempty"`
	// REQUIRED.
	// Tells to the gateway if the client should be exposed directly to the download_endpoint.
	Expose               bool     `protobuf:"varint,4,opt,name=expose,proto3" json:"expose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDownloadProtocol) Reset()         { *m = FileDownloadProtocol{} }
func (m *FileDownloadProtocol) String() string { return proto.CompactTextString(m) }
func (*FileDownloadProtocol) ProtoMessage()    {}
func (*FileDownloadProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{12}
}

func (m *FileDownloadProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDownloadProtocol.Unmarshal(m, b)
}
func (m *FileDownloadProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDownloadProtocol.Marshal(b, m, deterministic)
}
func (m *FileDownloadProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDownloadProtocol.Merge(m, src)
}
func (m *FileDownloadProtocol) XXX_Size() int {
	return xxx_messageInfo_FileDownloadProtocol.Size(m)
}
func (m *FileDownloadProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDownloadProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_FileDownloadProtocol proto.InternalMessageInfo

func (m *FileDownloadProtocol) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *FileDownloadProtocol) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *FileDownloadProtocol) GetDownloadEndpoint() string {
	if m != nil {
		return m.DownloadEndpoint
	}
	return ""
}

func (m *FileDownloadProtocol) GetExpose() bool {
	if m != nil {
		return m.Expose
	}
	return false
}

// Represents a storage space which could be a 'home', 'share' etc...
type StorageSpace struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	Id *StorageSpaceId `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// OPTIONAL.
	Owner *v1beta11.User `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	// OPTIONAL.
	// The root resource of the storage space.
	Root *Reference `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	// OPTIONAL.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// OPTIONAL.
	Quota *Quota `protobuf:"bytes,6,opt,name=quota,proto3" json:"quota,omitempty"`
	// OPTIONAL.
	// Could be 'home', 'share', 'project', 'space'...
	SpaceType string `protobuf:"bytes,7,opt,name=space_type,json=spaceType,proto3" json:"space_type,omitempty"`
	// OPTIONAL.
	// Last modification time (mtime) of the root resource of this storage space.
	Mtime                *v1beta1.Timestamp `protobuf:"bytes,8,opt,name=mtime,proto3" json:"mtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StorageSpace) Reset()         { *m = StorageSpace{} }
func (m *StorageSpace) String() string { return proto.CompactTextString(m) }
func (*StorageSpace) ProtoMessage()    {}
func (*StorageSpace) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{13}
}

func (m *StorageSpace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageSpace.Unmarshal(m, b)
}
func (m *StorageSpace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageSpace.Marshal(b, m, deterministic)
}
func (m *StorageSpace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageSpace.Merge(m, src)
}
func (m *StorageSpace) XXX_Size() int {
	return xxx_messageInfo_StorageSpace.Size(m)
}
func (m *StorageSpace) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageSpace.DiscardUnknown(m)
}

var xxx_messageInfo_StorageSpace proto.InternalMessageInfo

func (m *StorageSpace) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *StorageSpace) GetId() *StorageSpaceId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *StorageSpace) GetOwner() *v1beta11.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *StorageSpace) GetRoot() *Reference {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *StorageSpace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StorageSpace) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

func (m *StorageSpace) GetSpaceType() string {
	if m != nil {
		return m.SpaceType
	}
	return ""
}

func (m *StorageSpace) GetMtime() *v1beta1.Timestamp {
	if m != nil {
		return m.Mtime
	}
	return nil
}

// The id of a storage space.
type StorageSpaceId struct {
	// REQUIRED.
	// The internal storage space id.
	OpaqueId             string   `protobuf:"bytes,1,opt,name=opaque_id,json=opaqueId,proto3" json:"opaque_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageSpaceId) Reset()         { *m = StorageSpaceId{} }
func (m *StorageSpaceId) String() string { return proto.CompactTextString(m) }
func (*StorageSpaceId) ProtoMessage()    {}
func (*StorageSpaceId) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{14}
}

func (m *StorageSpaceId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageSpaceId.Unmarshal(m, b)
}
func (m *StorageSpaceId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageSpaceId.Marshal(b, m, deterministic)
}
func (m *StorageSpaceId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageSpaceId.Merge(m, src)
}
func (m *StorageSpaceId) XXX_Size() int {
	return xxx_messageInfo_StorageSpaceId.Size(m)
}
func (m *StorageSpaceId) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageSpaceId.DiscardUnknown(m)
}

var xxx_messageInfo_StorageSpaceId proto.InternalMessageInfo

func (m *StorageSpaceId) GetOpaqueId() string {
	if m != nil {
		return m.OpaqueId
	}
	return ""
}

// Represents a quota for a storage space.
type Quota struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// OPTIONAL.
	// The bytes quota for the user.
	QuotaMaxBytes uint64 `protobuf:"varint,2,opt,name=quota_max_bytes,json=quotaMaxBytes,proto3" json:"quota_max_bytes,omitempty"`
	// OPTIONAL.
	// The files quota for the user.
	QuotaMaxFiles        uint64   `protobuf:"varint,3,opt,name=quota_max_files,json=quotaMaxFiles,proto3" json:"quota_max_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quota) Reset()         { *m = Quota{} }
func (m *Quota) String() string { return proto.CompactTextString(m) }
func (*Quota) ProtoMessage()    {}
func (*Quota) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91600c359c2e479, []int{15}
}

func (m *Quota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quota.Unmarshal(m, b)
}
func (m *Quota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quota.Marshal(b, m, deterministic)
}
func (m *Quota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quota.Merge(m, src)
}
func (m *Quota) XXX_Size() int {
	return xxx_messageInfo_Quota.Size(m)
}
func (m *Quota) XXX_DiscardUnknown() {
	xxx_messageInfo_Quota.DiscardUnknown(m)
}

var xxx_messageInfo_Quota proto.InternalMessageInfo

func (m *Quota) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *Quota) GetQuotaMaxBytes() uint64 {
	if m != nil {
		return m.QuotaMaxBytes
	}
	return 0
}

func (m *Quota) GetQuotaMaxFiles() uint64 {
	if m != nil {
		return m.QuotaMaxFiles
	}
	return 0
}

func init() {
	proto.RegisterEnum("cs3.storage.provider.v1beta1.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterEnum("cs3.storage.provider.v1beta1.ResourceChecksumType", ResourceChecksumType_name, ResourceChecksumType_value)
	proto.RegisterEnum("cs3.storage.provider.v1beta1.GranteeType", GranteeType_name, GranteeType_value)
	proto.RegisterType((*ResourceInfo)(nil), "cs3.storage.provider.v1beta1.ResourceInfo")
	proto.RegisterType((*CanonicalMetadata)(nil), "cs3.storage.provider.v1beta1.CanonicalMetadata")
	proto.RegisterType((*ArbitraryMetadata)(nil), "cs3.storage.provider.v1beta1.ArbitraryMetadata")
	proto.RegisterMapType((map[string]string)(nil), "cs3.storage.provider.v1beta1.ArbitraryMetadata.MetadataEntry")
	proto.RegisterType((*ResourceChecksum)(nil), "cs3.storage.provider.v1beta1.ResourceChecksum")
	proto.RegisterType((*ResourceChecksumPriority)(nil), "cs3.storage.provider.v1beta1.ResourceChecksumPriority")
	proto.RegisterType((*Reference)(nil), "cs3.storage.provider.v1beta1.Reference")
	proto.RegisterType((*ResourcePermissions)(nil), "cs3.storage.provider.v1beta1.ResourcePermissions")
	proto.RegisterType((*Grant)(nil), "cs3.storage.provider.v1beta1.Grant")
	proto.RegisterType((*Grantee)(nil), "cs3.storage.provider.v1beta1.Grantee")
	proto.RegisterType((*FileVersion)(nil), "cs3.storage.provider.v1beta1.FileVersion")
	proto.RegisterType((*RecycleItem)(nil), "cs3.storage.provider.v1beta1.RecycleItem")
	proto.RegisterType((*FileUploadProtocol)(nil), "cs3.storage.provider.v1beta1.FileUploadProtocol")
	proto.RegisterType((*FileDownloadProtocol)(nil), "cs3.storage.provider.v1beta1.FileDownloadProtocol")
	proto.RegisterType((*StorageSpace)(nil), "cs3.storage.provider.v1beta1.StorageSpace")
	proto.RegisterType((*StorageSpaceId)(nil), "cs3.storage.provider.v1beta1.StorageSpaceId")
	proto.RegisterType((*Quota)(nil), "cs3.storage.provider.v1beta1.Quota")
}

func init() {
	proto.RegisterFile("cs3/storage/provider/v1beta1/resources.proto", fileDescriptor_b91600c359c2e479)
}

var fileDescriptor_b91600c359c2e479 = []byte{
	// 1671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xcd, 0x73, 0xdb, 0xc6,
	0x15, 0x0f, 0xf8, 0x25, 0xf0, 0xe9, 0x0b, 0x5a, 0x2b, 0x0e, 0x2c, 0x3b, 0xb1, 0x82, 0x4c, 0x1a,
	0x59, 0x75, 0xa9, 0x48, 0x6a, 0x9a, 0xa6, 0x49, 0x9a, 0x4a, 0x34, 0x6c, 0xb3, 0x91, 0x64, 0x76,
	0x49, 0xb9, 0x75, 0xc7, 0x53, 0xcc, 0x0a, 0x58, 0xd1, 0x98, 0x90, 0x00, 0x02, 0x2c, 0x15, 0xb3,
	0x87, 0xce, 0xf4, 0xd8, 0xce, 0x74, 0xa6, 0x97, 0x1e, 0x7b, 0xe9, 0x34, 0x97, 0xf4, 0xd6, 0xff,
	0xa0, 0xd7, 0xfe, 0x55, 0x9d, 0x7d, 0xbb, 0x20, 0x41, 0xc9, 0x92, 0x25, 0x4d, 0x3b, 0xbd, 0xed,
	0xbe, 0xef, 0xf7, 0x16, 0xef, 0xbd, 0x1f, 0xe0, 0xbe, 0x9f, 0x6d, 0x6f, 0x64, 0x22, 0x4e, 0x59,
	0x8f, 0x6f, 0x24, 0x69, 0x7c, 0x12, 0x06, 0x3c, 0xdd, 0x38, 0xd9, 0x3c, 0xe2, 0x82, 0x6d, 0x6e,
	0xa4, 0x3c, 0x8b, 0x87, 0xa9, 0xcf, 0xb3, 0x46, 0x92, 0xc6, 0x22, 0x26, 0x77, 0xfc, 0x6c, 0xbb,
	0xa1, 0xa5, 0x1b, 0xb9, 0x74, 0x43, 0x4b, 0xaf, 0xac, 0x4b, 0x5b, 0x61, 0xc0, 0x23, 0x11, 0x8a,
	0xd1, 0x46, 0x2f, 0x8d, 0x87, 0xc9, 0x79, 0x96, 0x56, 0xee, 0x4d, 0xc9, 0x0e, 0xb3, 0xf3, 0x9d,
	0xae, 0xbc, 0x2d, 0x45, 0xc5, 0x28, 0xe1, 0xd9, 0x58, 0x04, 0x6f, 0x8a, 0xed, 0x7c, 0x5b, 0x83,
	0x39, 0xaa, 0x55, 0x5a, 0xd1, 0x71, 0x4c, 0x36, 0xa1, 0x16, 0x27, 0xec, 0xeb, 0x21, 0xb7, 0x8d,
	0x55, 0x63, 0x6d, 0x76, 0xeb, 0x56, 0x43, 0x46, 0xad, 0x54, 0xb4, 0x81, 0xc6, 0x13, 0x14, 0xa0,
	0x5a, 0x90, 0xfc, 0x14, 0x2a, 0x92, 0x6f, 0x97, 0x56, 0x8d, 0xb5, 0x85, 0xad, 0xf5, 0xc6, 0x45,
	0x69, 0x36, 0x72, 0x67, 0xdd, 0x51, 0xc2, 0x29, 0xea, 0x91, 0x8f, 0xa1, 0x14, 0x06, 0x76, 0x19,
	0xdd, 0x7d, 0xf0, 0x3a, 0xed, 0x63, 0x9e, 0xf2, 0xc8, 0xe7, 0xb4, 0x14, 0x06, 0xe4, 0xe7, 0x60,
	0xfa, 0x2f, 0xb8, 0xff, 0x55, 0x36, 0x1c, 0xd8, 0x15, 0x54, 0x6f, 0x5c, 0xce, 0x79, 0x53, 0x6b,
	0xd1, 0xb1, 0x3e, 0x21, 0x50, 0xe1, 0x82, 0xf5, 0xec, 0xea, 0xaa, 0xb1, 0x56, 0xa7, 0x78, 0x26,
	0xb7, 0xa1, 0x3e, 0x08, 0x07, 0xdc, 0xc3, 0xec, 0x6a, 0xc8, 0x30, 0x25, 0x41, 0xc6, 0x4e, 0xb6,
	0xa0, 0x3a, 0x10, 0xe1, 0x80, 0xdb, 0x33, 0xe8, 0xf9, 0xce, 0x2b, 0xea, 0xd4, 0x0d, 0x07, 0x3c,
	0x13, 0x6c, 0x90, 0x50, 0x25, 0x4a, 0x3e, 0x81, 0x72, 0xca, 0x8f, 0x6d, 0xf3, 0x6a, 0xa9, 0x4a,
	0x1d, 0xf2, 0x2b, 0x58, 0x48, 0x78, 0x3a, 0x08, 0xb3, 0x2c, 0x8c, 0x23, 0x2f, 0xe3, 0xc2, 0xae,
	0xa3, 0x95, 0xcd, 0xcb, 0x65, 0xdc, 0x1e, 0xeb, 0x66, 0x74, 0x7e, 0x62, 0xa8, 0xc3, 0x85, 0xcc,
	0x3c, 0x0b, 0x7f, 0xcb, 0x6d, 0x58, 0x35, 0xd6, 0x2a, 0x14, 0xcf, 0xe4, 0x63, 0xa8, 0xc6, 0xdf,
	0x44, 0x3c, 0xb5, 0x67, 0xd1, 0xc9, 0xbb, 0xe8, 0x24, 0xff, 0xe0, 0x1a, 0xf2, 0x83, 0x1b, 0x7b,
	0x38, 0xcc, 0x78, 0xda, 0x0a, 0xa8, 0x92, 0x27, 0x37, 0xa1, 0x26, 0x58, 0xda, 0xe3, 0xc2, 0x9e,
	0xc3, 0x7a, 0xe9, 0x1b, 0xf9, 0x0d, 0x10, 0x9f, 0x45, 0x71, 0x14, 0xfa, 0xac, 0xef, 0x0d, 0xb8,
	0x60, 0x01, 0x13, 0xcc, 0x9e, 0x47, 0xeb, 0x1b, 0x17, 0xa7, 0xd0, 0xcc, 0xf5, 0xf6, 0xb5, 0x1a,
	0x5d, 0xf2, 0x4f, 0x93, 0xa4, 0x7d, 0x96, 0x1e, 0x85, 0x22, 0x65, 0xe9, 0x68, 0x62, 0x7f, 0xe1,
	0x32, 0xf6, 0x77, 0x72, 0xbd, 0x89, 0x7d, 0x76, 0x9a, 0xe4, 0x74, 0x61, 0xe9, 0x4c, 0x1c, 0xe4,
	0x8b, 0x71, 0xb2, 0xc6, 0xd5, 0x5e, 0x54, 0xab, 0x39, 0xff, 0x30, 0x60, 0xe9, 0x8c, 0x7b, 0xf2,
	0x0c, 0xcc, 0x71, 0x06, 0xc6, 0x6a, 0x79, 0x6d, 0x76, 0xeb, 0xf3, 0x2b, 0x66, 0xd0, 0xc8, 0x0f,
	0x6e, 0x24, 0xd2, 0x11, 0x1d, 0x9b, 0x5b, 0xf9, 0x14, 0xe6, 0xa7, 0x58, 0xc4, 0x82, 0xf2, 0x57,
	0x7c, 0x84, 0xf1, 0xd7, 0xa9, 0x3c, 0x92, 0x65, 0xa8, 0x9e, 0xb0, 0xfe, 0x50, 0xb5, 0x73, 0x9d,
	0xaa, 0xcb, 0x4f, 0x4a, 0x3f, 0x36, 0x9c, 0x3e, 0x58, 0xa7, 0x1b, 0x88, 0x3c, 0xd4, 0xbd, 0x6f,
	0x60, 0xef, 0x6f, 0x5d, 0xad, 0xfd, 0x0a, 0x33, 0xc0, 0x82, 0xb2, 0xec, 0x62, 0xe5, 0x53, 0x1e,
	0x9d, 0xdf, 0x81, 0x7d, 0x5a, 0xbe, 0x9d, 0x86, 0x71, 0x1a, 0x8a, 0xd1, 0x7f, 0xcd, 0xeb, 0x0a,
	0x98, 0x89, 0xb6, 0x89, 0xae, 0xe7, 0xe9, 0xf8, 0xee, 0xfc, 0x12, 0xea, 0xe3, 0x07, 0x23, 0x6f,
	0x03, 0x68, 0xfb, 0x5e, 0x18, 0xe8, 0x6a, 0xd5, 0x35, 0xa5, 0x15, 0x90, 0xb7, 0x60, 0x26, 0x8a,
	0x03, 0xe4, 0xa9, 0x0c, 0x6a, 0xf2, 0xda, 0x0a, 0x64, 0x6f, 0x25, 0x4c, 0xbc, 0xc0, 0xe1, 0x56,
	0xa7, 0x78, 0x76, 0xbe, 0xad, 0xc2, 0x8d, 0x57, 0xb4, 0xa5, 0x9c, 0x36, 0x2c, 0x08, 0xbc, 0x5e,
	0xca, 0x22, 0xf5, 0x41, 0x99, 0xd4, 0x64, 0x41, 0xf0, 0x48, 0xde, 0xc9, 0x3d, 0xb0, 0xfc, 0x94,
	0x33, 0xc1, 0x3d, 0x3f, 0x8e, 0x04, 0x0b, 0x65, 0x6f, 0x96, 0x50, 0x66, 0x51, 0xd1, 0x9b, 0x39,
	0x59, 0xb6, 0x60, 0xc0, 0xfb, 0x5c, 0x70, 0xf4, 0x6a, 0x52, 0x7d, 0x23, 0xb7, 0xc0, 0xec, 0x71,
	0xe1, 0x61, 0x3c, 0x55, 0xe4, 0xcc, 0xf4, 0xb8, 0x68, 0x33, 0xf1, 0x42, 0xba, 0x96, 0xac, 0xaf,
	0x87, 0xb1, 0x60, 0x38, 0xe8, 0x4c, 0x2a, 0x65, 0x7f, 0x21, 0xef, 0xe4, 0x87, 0x70, 0x33, 0x8c,
	0x42, 0x11, 0x4a, 0xe7, 0xc7, 0x61, 0x9f, 0x7b, 0x41, 0xfc, 0x4d, 0xd4, 0x8f, 0x59, 0x80, 0x93,
	0xcf, 0xa4, 0xcb, 0x39, 0xf7, 0x61, 0xd8, 0xe7, 0x0f, 0x34, 0x8f, 0x7c, 0x08, 0xcb, 0xd3, 0x5a,
	0xc3, 0x04, 0x75, 0x4c, 0xd4, 0x21, 0x45, 0x9d, 0x43, 0xe4, 0x90, 0xbb, 0x30, 0xdb, 0x0f, 0x33,
	0xa1, 0x0a, 0x90, 0xe1, 0x78, 0x33, 0x29, 0x48, 0x12, 0x96, 0x20, 0x23, 0xef, 0xc3, 0x02, 0x0a,
	0x4c, 0x2a, 0x00, 0x28, 0x33, 0x2f, 0xa9, 0x93, 0xfc, 0xef, 0x03, 0x41, 0x31, 0xf4, 0x7a, 0xc2,
	0x53, 0xac, 0x2e, 0x0e, 0x32, 0x93, 0x5a, 0x92, 0x23, 0x7d, 0x3e, 0xd5, 0x74, 0xf2, 0x2e, 0xcc,
	0xa1, 0x74, 0xca, 0xfd, 0x91, 0xdf, 0xe7, 0x38, 0xb6, 0x4c, 0x8a, 0x91, 0x50, 0x45, 0x92, 0x8f,
	0x38, 0x88, 0x4f, 0x38, 0x4e, 0x2b, 0x93, 0xe2, 0x59, 0xaa, 0xa5, 0x5c, 0x9e, 0xf4, 0x7b, 0x2d,
	0x28, 0x35, 0x45, 0x53, 0x4f, 0xf6, 0x1e, 0xcc, 0x27, 0xc3, 0xb4, 0xc7, 0xc7, 0xa6, 0x17, 0x51,
	0x66, 0x0e, 0x89, 0xb9, 0xed, 0x0f, 0x61, 0x39, 0xe5, 0xf2, 0x43, 0xe2, 0x53, 0xf1, 0xda, 0x96,
	0x2a, 0x93, 0xe6, 0x15, 0x22, 0x2e, 0x6a, 0x68, 0xc3, 0x5e, 0x28, 0xf8, 0xc0, 0x5e, 0x9a, 0xd2,
	0xd0, 0xf6, 0x5b, 0x82, 0xe3, 0x6a, 0xcb, 0x04, 0x13, 0x36, 0x51, 0xf1, 0xcb, 0xb3, 0x8c, 0x7f,
	0x98, 0x04, 0xf2, 0x71, 0x54, 0xfc, 0x37, 0x54, 0xfc, 0x8a, 0x86, 0xf1, 0x3b, 0x7f, 0x35, 0xa0,
	0xaa, 0x32, 0xf9, 0x02, 0x66, 0x50, 0x8a, 0xe7, 0xa0, 0xe0, 0xfd, 0x8b, 0x3b, 0xee, 0x91, 0x12,
	0xa6, 0xb9, 0x16, 0xe9, 0xc0, 0xec, 0x64, 0xe7, 0x64, 0xf8, 0xe1, 0x5e, 0x6b, 0x73, 0x15, 0xad,
	0x38, 0xbf, 0x2f, 0xc1, 0x8c, 0xf6, 0x44, 0x3e, 0x9f, 0x1a, 0x08, 0xf7, 0x2e, 0x15, 0x5e, 0x61,
	0x0e, 0x7c, 0x06, 0x33, 0x72, 0xa7, 0x79, 0x63, 0x18, 0xf2, 0xfa, 0x85, 0xf7, 0xf8, 0x0d, 0x5a,
	0x1b, 0xe2, 0x89, 0xfc, 0x0c, 0x4c, 0x84, 0x6b, 0x52, 0x5d, 0xc1, 0x90, 0xf7, 0xa6, 0xd5, 0x91,
	0x5b, 0x70, 0x1f, 0x0f, 0x13, 0x34, 0x30, 0xd3, 0x53, 0xc7, 0x02, 0xe8, 0xaa, 0x5e, 0x12, 0x74,
	0xed, 0x56, 0x24, 0x68, 0x72, 0xfe, 0x6c, 0xc0, 0x6c, 0xf1, 0xe3, 0xb8, 0x06, 0x7a, 0xd3, 0x1b,
	0xa0, 0x3c, 0xd9, 0x00, 0x39, 0x20, 0xa8, 0x14, 0x00, 0xc1, 0x72, 0x8e, 0x76, 0xaa, 0x48, 0xd4,
	0x78, 0x26, 0x07, 0x4d, 0xb5, 0x09, 0x68, 0x72, 0xfe, 0x5e, 0x82, 0xd9, 0xe2, 0xd7, 0xf7, 0x7f,
	0x00, 0x94, 0x67, 0x53, 0xd2, 0xc0, 0xab, 0x72, 0x0d, 0xe0, 0x95, 0x57, 0xa3, 0x5a, 0xa8, 0xc6,
	0x0e, 0xcc, 0xe3, 0x50, 0x95, 0x50, 0x0c, 0xab, 0x52, 0xbb, 0x04, 0x06, 0x9c, 0xcb, 0x55, 0x24,
	0xc9, 0xf9, 0x53, 0x09, 0xc8, 0x64, 0xf8, 0xb5, 0x25, 0x18, 0xf7, 0xe3, 0xfe, 0x75, 0xaa, 0x85,
	0x4b, 0x4c, 0xa9, 0xeb, 0xed, 0x33, 0xbe, 0x93, 0x0f, 0x60, 0x51, 0xcd, 0x5d, 0x8f, 0x47, 0x41,
	0x12, 0x87, 0x91, 0xd0, 0x55, 0x59, 0x50, 0x64, 0x57, 0x53, 0x49, 0x0f, 0x6e, 0xb0, 0x13, 0x16,
	0xf6, 0xd9, 0x51, 0x9f, 0x7b, 0x39, 0x28, 0xce, 0xec, 0x0a, 0xc2, 0x8f, 0x1f, 0x5d, 0x6d, 0xc1,
	0xe6, 0x6b, 0x9a, 0x92, 0xb1, 0xc9, 0x9c, 0x95, 0xc9, 0xed, 0xc4, 0x5f, 0x26, 0x71, 0xc6, 0xf5,
	0x0e, 0xd2, 0x37, 0xe7, 0x3b, 0x03, 0x96, 0x8b, 0x0b, 0xe4, 0x7f, 0x55, 0x91, 0xef, 0xc3, 0x52,
	0xbe, 0xbf, 0x4e, 0xd7, 0xc4, 0xca, 0x19, 0xe3, 0xaa, 0x4c, 0x82, 0xad, 0x4c, 0x05, 0xfb, 0x97,
	0x32, 0xcc, 0x75, 0x54, 0x39, 0x3a, 0x09, 0xf3, 0xf9, 0x75, 0x82, 0xfc, 0x0c, 0xff, 0x7a, 0xd4,
	0x28, 0xbc, 0x7f, 0x71, 0x81, 0x8b, 0xae, 0x5a, 0x01, 0xfe, 0xfa, 0x7c, 0x94, 0x03, 0x74, 0x35,
	0xaf, 0xee, 0xbe, 0x66, 0x5e, 0xe5, 0xf0, 0xfc, 0x53, 0xa8, 0xa4, 0x71, 0x2c, 0xae, 0xda, 0x08,
	0xa8, 0x24, 0x3b, 0x21, 0x62, 0x7a, 0x04, 0xd4, 0x29, 0x9e, 0xc9, 0x27, 0x50, 0x9d, 0xa0, 0x86,
	0x7c, 0xf0, 0x9d, 0x6b, 0x11, 0x01, 0x05, 0x55, 0x1a, 0x88, 0xa9, 0x64, 0x46, 0xea, 0xf7, 0x6a,
	0x46, 0x63, 0x2a, 0x49, 0x99, 0xfe, 0xbf, 0x32, 0x2f, 0xfd, 0x7f, 0xe5, 0xfc, 0x00, 0x16, 0xa6,
	0x6b, 0x25, 0x91, 0x8d, 0xaa, 0xf7, 0x04, 0xb7, 0x99, 0x8a, 0xd0, 0x0a, 0x9c, 0x3f, 0x1a, 0x50,
	0x55, 0x18, 0xe7, 0x1a, 0xef, 0xf7, 0x3d, 0x58, 0xc4, 0x3c, 0xbc, 0x01, 0x7b, 0xe9, 0x1d, 0x8d,
	0x04, 0x57, 0x7b, 0xad, 0x42, 0xe7, 0x91, 0xbc, 0xcf, 0x5e, 0xee, 0x4a, 0xe2, 0xb4, 0x9c, 0xdc,
	0xf1, 0x19, 0xbe, 0x59, 0x41, 0x4e, 0x7e, 0xf6, 0xd9, 0xfa, 0x3f, 0x8d, 0xc9, 0x9f, 0x38, 0x16,
	0xe0, 0x16, 0xbc, 0x49, 0xdd, 0xce, 0x93, 0x43, 0xda, 0x74, 0xbd, 0xee, 0xb3, 0xb6, 0xeb, 0xb5,
	0x0e, 0x9e, 0xee, 0xec, 0xb5, 0x1e, 0x58, 0x6f, 0x90, 0x9b, 0x40, 0xa6, 0x59, 0x0f, 0x5b, 0x7b,
	0xae, 0x65, 0x90, 0xdb, 0xf0, 0xd6, 0x34, 0xbd, 0xf9, 0xe4, 0xa0, 0xbb, 0xd3, 0x3a, 0x70, 0xa9,
	0x55, 0x3a, 0xcb, 0xa4, 0xee, 0x43, 0x97, 0xba, 0x07, 0x4d, 0xd7, 0x2a, 0x9f, 0x75, 0xd6, 0x79,
	0xb6, 0xbf, 0xd7, 0x3a, 0xf8, 0xd2, 0xaa, 0x90, 0x15, 0xb8, 0x79, 0x3a, 0x8e, 0xae, 0x4b, 0x0f,
	0x76, 0xf6, 0xac, 0xea, 0xfa, 0xbf, 0x0c, 0x58, 0x7e, 0x15, 0xbe, 0x26, 0x0e, 0xbc, 0x33, 0x56,
	0x6a, 0x3e, 0x76, 0x9b, 0x5f, 0x76, 0x0e, 0xf7, 0x4f, 0x67, 0xb1, 0x0a, 0x77, 0xce, 0x91, 0x39,
	0x3c, 0xe8, 0xb8, 0x5d, 0xcb, 0xb8, 0xc0, 0xca, 0xce, 0x83, 0x3d, 0x97, 0x6e, 0x6f, 0x59, 0x25,
	0xf2, 0x0e, 0xac, 0x9c, 0x23, 0xb3, 0xff, 0xe0, 0x23, 0xab, 0x4c, 0xee, 0xc2, 0xed, 0x73, 0xf8,
	0x9d, 0xc7, 0x3b, 0x9b, 0x56, 0x65, 0xfd, 0x29, 0xcc, 0x16, 0x10, 0x01, 0xb1, 0x61, 0xf9, 0x11,
	0xdd, 0x39, 0xe8, 0xba, 0x67, 0xaa, 0xfe, 0x26, 0x2c, 0x4d, 0x71, 0x0e, 0x3b, 0x2e, 0xb5, 0x0c,
	0xf9, 0x18, 0x53, 0xe4, 0x47, 0xf4, 0xc9, 0x61, 0xdb, 0x2a, 0xed, 0xfe, 0xc1, 0x80, 0x55, 0x3f,
	0x1e, 0x5c, 0xd8, 0x11, 0xbb, 0x0b, 0x79, 0xf5, 0x32, 0x1c, 0x78, 0x6d, 0xe3, 0xd7, 0x8b, 0xb9,
	0x8c, 0x16, 0xf9, 0x5b, 0xa9, 0xdc, 0xec, 0xb4, 0xbf, 0x2b, 0xdd, 0x69, 0x66, 0xdb, 0xf9, 0x24,
	0x68, 0xb4, 0x73, 0x3b, 0x4f, 0x37, 0x77, 0xa5, 0xd0, 0xbf, 0x91, 0xfd, 0x5c, 0xb3, 0x9f, 0xe7,
	0xec, 0xe7, 0x9a, 0x7d, 0x54, 0xc3, 0xf9, 0xb7, 0xfd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e,
	0xa1, 0xec, 0x24, 0xb1, 0x12, 0x00, 0x00,
}
